<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Authentication;

use CalendarApiLib\Models\OauthScope;
use CalendarApiLib\Models\OauthToken;
use Core\Utils\CoreHelper;

/**
 * Utility class for initializing AuthorizationCodeAuth security credentials.
 */
class AuthorizationCodeAuthCredentialsBuilder
{
    /**
     * @var array
     */
    private $config;

    private function __construct(array $config)
    {
        $this->config = $config;
    }

    /**
     * Initializer for AuthorizationCodeAuthCredentialsBuilder
     *
     * @param string $oauthClientId
     * @param string $oauthClientSecret
     * @param string $oauthRedirectUri
     */
    public static function init(string $oauthClientId, string $oauthClientSecret, string $oauthRedirectUri): self
    {
        return new self([
            'oauthClientId' => $oauthClientId,
            'oauthClientSecret' => $oauthClientSecret,
            'oauthRedirectUri' => $oauthRedirectUri
        ]);
    }

    /**
     * Setter for OauthClientId.
     *
     * @param string $oauthClientId
     *
     * @return $this
     */
    public function oauthClientId(string $oauthClientId): self
    {
        $this->config['oauthClientId'] = $oauthClientId;
        return $this;
    }

    /**
     * Setter for OauthClientSecret.
     *
     * @param string $oauthClientSecret
     *
     * @return $this
     */
    public function oauthClientSecret(string $oauthClientSecret): self
    {
        $this->config['oauthClientSecret'] = $oauthClientSecret;
        return $this;
    }

    /**
     * Setter for OauthRedirectUri.
     *
     * @param string $oauthRedirectUri
     *
     * @return $this
     */
    public function oauthRedirectUri(string $oauthRedirectUri): self
    {
        $this->config['oauthRedirectUri'] = $oauthRedirectUri;
        return $this;
    }

    /**
     * Setter for OauthToken.
     *
     * @param OauthToken|null $oauthToken
     *
     * @return $this
     */
    public function oauthToken(?OauthToken $oauthToken): self
    {
        $this->config['oauthToken'] = $oauthToken;
        return $this;
    }

    /**
     * Setter for OauthScopes.
     *
     * @param string[]|null $oauthScopes
     *
     * @return $this
     */
    public function oauthScopes(?array $oauthScopes): self
    {
        OauthScope::checkValue($oauthScopes);
        $this->config['oauthScopes'] = $oauthScopes;
        return $this;
    }

    /**
     * Setter for clock skew time in seconds applied while checking the OAuth Token expiry.
     *
     * @param int $oauthClockSkew
     *
     * @return $this
     */
    public function oauthClockSkew(int $oauthClockSkew): self
    {
        $this->config['oauth2-ClockSkew'] = $oauthClockSkew;
        return $this;
    }

    public function getConfiguration(): array
    {
        return CoreHelper::clone($this->config);
    }
}
