<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models\Builders;

use CalendarApiLib\Models\Attachment;
use Core\Utils\CoreHelper;

/**
 * Builder for model Attachment
 *
 * @see Attachment
 */
class AttachmentBuilder
{
    /**
     * @var Attachment
     */
    private $instance;

    private function __construct(Attachment $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Attachment Builder object.
     */
    public static function init(): self
    {
        return new self(new Attachment());
    }

    /**
     * Sets file Url field.
     *
     * @param string|null $value
     */
    public function fileUrl(?string $value): self
    {
        $this->instance->setFileUrl($value);
        return $this;
    }

    /**
     * Sets title field.
     *
     * @param string|null $value
     */
    public function title(?string $value): self
    {
        $this->instance->setTitle($value);
        return $this;
    }

    /**
     * Sets mime Type field.
     *
     * @param string|null $value
     */
    public function mimeType(?string $value): self
    {
        $this->instance->setMimeType($value);
        return $this;
    }

    /**
     * Sets icon Link field.
     *
     * @param string|null $value
     */
    public function iconLink(?string $value): self
    {
        $this->instance->setIconLink($value);
        return $this;
    }

    /**
     * Sets file Id field.
     *
     * @param string|null $value
     */
    public function fileId(?string $value): self
    {
        $this->instance->setFileId($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Attachment object.
     */
    public function build(): Attachment
    {
        return CoreHelper::clone($this->instance);
    }
}
