<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models\Builders;

use CalendarApiLib\Models\Attendee;
use Core\Utils\CoreHelper;

/**
 * Builder for model Attendee
 *
 * @see Attendee
 */
class AttendeeBuilder
{
    /**
     * @var Attendee
     */
    private $instance;

    private function __construct(Attendee $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Attendee Builder object.
     */
    public static function init(): self
    {
        return new self(new Attendee());
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets email field.
     *
     * @param string|null $value
     */
    public function email(?string $value): self
    {
        $this->instance->setEmail($value);
        return $this;
    }

    /**
     * Sets display Name field.
     *
     * @param string|null $value
     */
    public function displayName(?string $value): self
    {
        $this->instance->setDisplayName($value);
        return $this;
    }

    /**
     * Sets organizer field.
     *
     * @param bool|null $value
     */
    public function organizer(?bool $value): self
    {
        $this->instance->setOrganizer($value);
        return $this;
    }

    /**
     * Sets self field.
     *
     * @param bool|null $value
     */
    public function self(?bool $value): self
    {
        $this->instance->setSelf($value);
        return $this;
    }

    /**
     * Sets resource field.
     *
     * @param bool|null $value
     */
    public function resource(?bool $value): self
    {
        $this->instance->setResource($value);
        return $this;
    }

    /**
     * Sets optional field.
     *
     * @param bool|null $value
     */
    public function optional(?bool $value): self
    {
        $this->instance->setOptional($value);
        return $this;
    }

    /**
     * Sets response Status field.
     *
     * @param string|null $value
     */
    public function responseStatus(?string $value): self
    {
        $this->instance->setResponseStatus($value);
        return $this;
    }

    /**
     * Sets comment field.
     *
     * @param string|null $value
     */
    public function comment(?string $value): self
    {
        $this->instance->setComment($value);
        return $this;
    }

    /**
     * Sets additional Guests field.
     *
     * @param int|null $value
     */
    public function additionalGuests(?int $value): self
    {
        $this->instance->setAdditionalGuests($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Attendee object.
     */
    public function build(): Attendee
    {
        return CoreHelper::clone($this->instance);
    }
}
