<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models\Builders;

use CalendarApiLib\Models\BirthdayProperties;
use Core\Utils\CoreHelper;

/**
 * Builder for model BirthdayProperties
 *
 * @see BirthdayProperties
 */
class BirthdayPropertiesBuilder
{
    /**
     * @var BirthdayProperties
     */
    private $instance;

    private function __construct(BirthdayProperties $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Birthday Properties Builder object.
     */
    public static function init(): self
    {
        return new self(new BirthdayProperties());
    }

    /**
     * Sets contact field.
     *
     * @param string|null $value
     */
    public function contact(?string $value): self
    {
        $this->instance->setContact($value);
        return $this;
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets custom Type Name field.
     *
     * @param string|null $value
     */
    public function customTypeName(?string $value): self
    {
        $this->instance->setCustomTypeName($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Birthday Properties object.
     */
    public function build(): BirthdayProperties
    {
        return CoreHelper::clone($this->instance);
    }
}
