<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models\Builders;

use CalendarApiLib\Models\CalendarNotification;
use Core\Utils\CoreHelper;

/**
 * Builder for model CalendarNotification
 *
 * @see CalendarNotification
 */
class CalendarNotificationBuilder
{
    /**
     * @var CalendarNotification
     */
    private $instance;

    private function __construct(CalendarNotification $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Calendar Notification Builder object.
     */
    public static function init(): self
    {
        return new self(new CalendarNotification());
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets method field.
     *
     * @param string|null $value
     */
    public function method(?string $value): self
    {
        $this->instance->setMethod($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Calendar Notification object.
     */
    public function build(): CalendarNotification
    {
        return CoreHelper::clone($this->instance);
    }
}
