<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models\Builders;

use CalendarApiLib\Models\CalendarListEntryNotificationSettings;
use CalendarApiLib\Models\CalendarNotification;
use Core\Utils\CoreHelper;

/**
 * Builder for model CalendarListEntryNotificationSettings
 *
 * @see CalendarListEntryNotificationSettings
 */
class CalendarListEntryNotificationSettingsBuilder
{
    /**
     * @var CalendarListEntryNotificationSettings
     */
    private $instance;

    private function __construct(CalendarListEntryNotificationSettings $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Calendar List Entry Notification Settings Builder object.
     */
    public static function init(): self
    {
        return new self(new CalendarListEntryNotificationSettings());
    }

    /**
     * Sets notifications field.
     *
     * @param CalendarNotification[]|null $value
     */
    public function notifications(?array $value): self
    {
        $this->instance->setNotifications($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Calendar List Entry Notification Settings object.
     */
    public function build(): CalendarListEntryNotificationSettings
    {
        return CoreHelper::clone($this->instance);
    }
}
