<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models\Builders;

use CalendarApiLib\Models\CalendarListEntryConferenceProperties;
use Core\Utils\CoreHelper;

/**
 * Builder for model CalendarListEntryConferenceProperties
 *
 * @see CalendarListEntryConferenceProperties
 */
class CalendarListEntryConferencePropertiesBuilder
{
    /**
     * @var CalendarListEntryConferenceProperties
     */
    private $instance;

    private function __construct(CalendarListEntryConferenceProperties $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Calendar List Entry Conference Properties Builder object.
     */
    public static function init(): self
    {
        return new self(new CalendarListEntryConferenceProperties());
    }

    /**
     * Sets allowed Conference Solution Types field.
     *
     * @param string[]|null $value
     */
    public function allowedConferenceSolutionTypes(?array $value): self
    {
        $this->instance->setAllowedConferenceSolutionTypes($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Calendar List Entry Conference Properties object.
     */
    public function build(): CalendarListEntryConferenceProperties
    {
        return CoreHelper::clone($this->instance);
    }
}
