<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models\Builders;

use CalendarApiLib\Models\CalendarListEntry;
use CalendarApiLib\Models\CalendarListEntryConferenceProperties;
use CalendarApiLib\Models\CalendarListEntryNotificationSettings;
use CalendarApiLib\Models\Reminder;
use Core\Utils\CoreHelper;

/**
 * Builder for model CalendarListEntry
 *
 * @see CalendarListEntry
 */
class CalendarListEntryBuilder
{
    /**
     * @var CalendarListEntry
     */
    private $instance;

    private function __construct(CalendarListEntry $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Calendar List Entry Builder object.
     */
    public static function init(): self
    {
        return new self(new CalendarListEntry());
    }

    /**
     * Sets kind field.
     *
     * @param string|null $value
     */
    public function kind(?string $value): self
    {
        $this->instance->setKind($value);
        return $this;
    }

    /**
     * Sets etag field.
     *
     * @param string|null $value
     */
    public function etag(?string $value): self
    {
        $this->instance->setEtag($value);
        return $this;
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets summary field.
     *
     * @param string|null $value
     */
    public function summary(?string $value): self
    {
        $this->instance->setSummary($value);
        return $this;
    }

    /**
     * Sets description field.
     *
     * @param string|null $value
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Sets location field.
     *
     * @param string|null $value
     */
    public function location(?string $value): self
    {
        $this->instance->setLocation($value);
        return $this;
    }

    /**
     * Sets time Zone field.
     *
     * @param string|null $value
     */
    public function timeZone(?string $value): self
    {
        $this->instance->setTimeZone($value);
        return $this;
    }

    /**
     * Sets summary Override field.
     *
     * @param string|null $value
     */
    public function summaryOverride(?string $value): self
    {
        $this->instance->setSummaryOverride($value);
        return $this;
    }

    /**
     * Sets color Id field.
     *
     * @param string|null $value
     */
    public function colorId(?string $value): self
    {
        $this->instance->setColorId($value);
        return $this;
    }

    /**
     * Sets background Color field.
     *
     * @param string|null $value
     */
    public function backgroundColor(?string $value): self
    {
        $this->instance->setBackgroundColor($value);
        return $this;
    }

    /**
     * Sets foreground Color field.
     *
     * @param string|null $value
     */
    public function foregroundColor(?string $value): self
    {
        $this->instance->setForegroundColor($value);
        return $this;
    }

    /**
     * Sets hidden field.
     *
     * @param bool|null $value
     */
    public function hidden(?bool $value): self
    {
        $this->instance->setHidden($value);
        return $this;
    }

    /**
     * Sets selected field.
     *
     * @param bool|null $value
     */
    public function selected(?bool $value): self
    {
        $this->instance->setSelected($value);
        return $this;
    }

    /**
     * Sets access Role field.
     *
     * @param string|null $value
     */
    public function accessRole(?string $value): self
    {
        $this->instance->setAccessRole($value);
        return $this;
    }

    /**
     * Sets default Reminders field.
     *
     * @param Reminder[]|null $value
     */
    public function defaultReminders(?array $value): self
    {
        $this->instance->setDefaultReminders($value);
        return $this;
    }

    /**
     * Sets notification Settings field.
     *
     * @param CalendarListEntryNotificationSettings|null $value
     */
    public function notificationSettings(?CalendarListEntryNotificationSettings $value): self
    {
        $this->instance->setNotificationSettings($value);
        return $this;
    }

    /**
     * Sets primary field.
     *
     * @param bool|null $value
     */
    public function primary(?bool $value): self
    {
        $this->instance->setPrimary($value);
        return $this;
    }

    /**
     * Sets deleted field.
     *
     * @param bool|null $value
     */
    public function deleted(?bool $value): self
    {
        $this->instance->setDeleted($value);
        return $this;
    }

    /**
     * Sets conference Properties field.
     *
     * @param CalendarListEntryConferenceProperties|null $value
     */
    public function conferenceProperties(?CalendarListEntryConferenceProperties $value): self
    {
        $this->instance->setConferenceProperties($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Calendar List Entry object.
     */
    public function build(): CalendarListEntry
    {
        return CoreHelper::clone($this->instance);
    }
}
