<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models\Builders;

use CalendarApiLib\Models\CalendarListEntry;
use CalendarApiLib\Models\CalendarListResponse;
use Core\Utils\CoreHelper;

/**
 * Builder for model CalendarListResponse
 *
 * @see CalendarListResponse
 */
class CalendarListResponseBuilder
{
    /**
     * @var CalendarListResponse
     */
    private $instance;

    private function __construct(CalendarListResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Calendar List Response Builder object.
     */
    public static function init(): self
    {
        return new self(new CalendarListResponse());
    }

    /**
     * Sets kind field.
     *
     * @param string|null $value
     */
    public function kind(?string $value): self
    {
        $this->instance->setKind($value);
        return $this;
    }

    /**
     * Sets etag field.
     *
     * @param string|null $value
     */
    public function etag(?string $value): self
    {
        $this->instance->setEtag($value);
        return $this;
    }

    /**
     * Sets next Page Token field.
     *
     * @param string|null $value
     */
    public function nextPageToken(?string $value): self
    {
        $this->instance->setNextPageToken($value);
        return $this;
    }

    /**
     * Sets next Sync Token field.
     *
     * @param string|null $value
     */
    public function nextSyncToken(?string $value): self
    {
        $this->instance->setNextSyncToken($value);
        return $this;
    }

    /**
     * Sets items field.
     *
     * @param CalendarListEntry[]|null $value
     */
    public function items(?array $value): self
    {
        $this->instance->setItems($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Calendar List Response object.
     */
    public function build(): CalendarListResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
