<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models\Builders;

use CalendarApiLib\Models\Channel;
use Core\Utils\CoreHelper;

/**
 * Builder for model Channel
 *
 * @see Channel
 */
class ChannelBuilder
{
    /**
     * @var Channel
     */
    private $instance;

    private function __construct(Channel $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Channel Builder object.
     */
    public static function init(): self
    {
        return new self(new Channel());
    }

    /**
     * Sets kind field.
     *
     * @param string|null $value
     */
    public function kind(?string $value): self
    {
        $this->instance->setKind($value);
        return $this;
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets resource Id field.
     *
     * @param string|null $value
     */
    public function resourceId(?string $value): self
    {
        $this->instance->setResourceId($value);
        return $this;
    }

    /**
     * Sets resource Uri field.
     *
     * @param string|null $value
     */
    public function resourceUri(?string $value): self
    {
        $this->instance->setResourceUri($value);
        return $this;
    }

    /**
     * Sets token field.
     *
     * @param string|null $value
     */
    public function token(?string $value): self
    {
        $this->instance->setToken($value);
        return $this;
    }

    /**
     * Sets expiration field.
     *
     * @param int|null $value
     */
    public function expiration(?int $value): self
    {
        $this->instance->setExpiration($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Channel object.
     */
    public function build(): Channel
    {
        return CoreHelper::clone($this->instance);
    }
}
