<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models\Builders;

use CalendarApiLib\Models\ChannelParams;
use Core\Utils\CoreHelper;

/**
 * Builder for model ChannelParams
 *
 * @see ChannelParams
 */
class ChannelParamsBuilder
{
    /**
     * @var ChannelParams
     */
    private $instance;

    private function __construct(ChannelParams $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Channel Params Builder object.
     */
    public static function init(): self
    {
        return new self(new ChannelParams());
    }

    /**
     * Sets ttl field.
     *
     * @param string|null $value
     */
    public function ttl(?string $value): self
    {
        $this->instance->setTtl($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Channel Params object.
     */
    public function build(): ChannelParams
    {
        return CoreHelper::clone($this->instance);
    }
}
