<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models\Builders;

use CalendarApiLib\Models\ConferenceCreateRequest;
use CalendarApiLib\Models\ConferenceCreateRequestStatus;
use CalendarApiLib\Models\ConferenceSolutionKey;
use Core\Utils\CoreHelper;

/**
 * Builder for model ConferenceCreateRequest
 *
 * @see ConferenceCreateRequest
 */
class ConferenceCreateRequestBuilder
{
    /**
     * @var ConferenceCreateRequest
     */
    private $instance;

    private function __construct(ConferenceCreateRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Conference Create Request Builder object.
     */
    public static function init(): self
    {
        return new self(new ConferenceCreateRequest());
    }

    /**
     * Sets request Id field.
     *
     * @param string|null $value
     */
    public function requestId(?string $value): self
    {
        $this->instance->setRequestId($value);
        return $this;
    }

    /**
     * Sets conference Solution Key field.
     *
     * @param ConferenceSolutionKey|null $value
     */
    public function conferenceSolutionKey(?ConferenceSolutionKey $value): self
    {
        $this->instance->setConferenceSolutionKey($value);
        return $this;
    }

    /**
     * Sets status field.
     *
     * @param ConferenceCreateRequestStatus|null $value
     */
    public function status(?ConferenceCreateRequestStatus $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Conference Create Request object.
     */
    public function build(): ConferenceCreateRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
