<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models\Builders;

use CalendarApiLib\Models\ConferenceCreateRequestStatus;
use Core\Utils\CoreHelper;

/**
 * Builder for model ConferenceCreateRequestStatus
 *
 * @see ConferenceCreateRequestStatus
 */
class ConferenceCreateRequestStatusBuilder
{
    /**
     * @var ConferenceCreateRequestStatus
     */
    private $instance;

    private function __construct(ConferenceCreateRequestStatus $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Conference Create Request Status Builder object.
     */
    public static function init(): self
    {
        return new self(new ConferenceCreateRequestStatus());
    }

    /**
     * Sets status Code field.
     *
     * @param string|null $value
     */
    public function statusCode(?string $value): self
    {
        $this->instance->setStatusCode($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Conference Create Request Status object.
     */
    public function build(): ConferenceCreateRequestStatus
    {
        return CoreHelper::clone($this->instance);
    }
}
