<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models\Builders;

use CalendarApiLib\Models\ConferenceCreateRequest;
use CalendarApiLib\Models\ConferenceData;
use CalendarApiLib\Models\ConferenceEntryPoint;
use CalendarApiLib\Models\ConferenceSolution;
use Core\Utils\CoreHelper;

/**
 * Builder for model ConferenceData
 *
 * @see ConferenceData
 */
class ConferenceDataBuilder
{
    /**
     * @var ConferenceData
     */
    private $instance;

    private function __construct(ConferenceData $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Conference Data Builder object.
     */
    public static function init(): self
    {
        return new self(new ConferenceData());
    }

    /**
     * Sets create Request field.
     *
     * @param ConferenceCreateRequest|null $value
     */
    public function createRequest(?ConferenceCreateRequest $value): self
    {
        $this->instance->setCreateRequest($value);
        return $this;
    }

    /**
     * Sets entry Points field.
     *
     * @param ConferenceEntryPoint[]|null $value
     */
    public function entryPoints(?array $value): self
    {
        $this->instance->setEntryPoints($value);
        return $this;
    }

    /**
     * Sets conference Solution field.
     *
     * @param ConferenceSolution|null $value
     */
    public function conferenceSolution(?ConferenceSolution $value): self
    {
        $this->instance->setConferenceSolution($value);
        return $this;
    }

    /**
     * Sets conference Id field.
     *
     * @param string|null $value
     */
    public function conferenceId(?string $value): self
    {
        $this->instance->setConferenceId($value);
        return $this;
    }

    /**
     * Sets notes field.
     *
     * @param string|null $value
     */
    public function notes(?string $value): self
    {
        $this->instance->setNotes($value);
        return $this;
    }

    /**
     * Sets signature field.
     *
     * @param string|null $value
     */
    public function signature(?string $value): self
    {
        $this->instance->setSignature($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Conference Data object.
     */
    public function build(): ConferenceData
    {
        return CoreHelper::clone($this->instance);
    }
}
