<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models\Builders;

use CalendarApiLib\Models\ConferenceSolutionKey;
use Core\Utils\CoreHelper;

/**
 * Builder for model ConferenceSolutionKey
 *
 * @see ConferenceSolutionKey
 */
class ConferenceSolutionKeyBuilder
{
    /**
     * @var ConferenceSolutionKey
     */
    private $instance;

    private function __construct(ConferenceSolutionKey $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Conference Solution Key Builder object.
     */
    public static function init(): self
    {
        return new self(new ConferenceSolutionKey());
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Conference Solution Key object.
     */
    public function build(): ConferenceSolutionKey
    {
        return CoreHelper::clone($this->instance);
    }
}
