<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models\Builders;

use CalendarApiLib\Models\ConferenceEntryPoint;
use Core\Utils\CoreHelper;

/**
 * Builder for model ConferenceEntryPoint
 *
 * @see ConferenceEntryPoint
 */
class ConferenceEntryPointBuilder
{
    /**
     * @var ConferenceEntryPoint
     */
    private $instance;

    private function __construct(ConferenceEntryPoint $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Conference Entry Point Builder object.
     */
    public static function init(): self
    {
        return new self(new ConferenceEntryPoint());
    }

    /**
     * Sets entry Point Type field.
     *
     * @param string|null $value
     */
    public function entryPointType(?string $value): self
    {
        $this->instance->setEntryPointType($value);
        return $this;
    }

    /**
     * Sets uri field.
     *
     * @param string|null $value
     */
    public function uri(?string $value): self
    {
        $this->instance->setUri($value);
        return $this;
    }

    /**
     * Sets label field.
     *
     * @param string|null $value
     */
    public function label(?string $value): self
    {
        $this->instance->setLabel($value);
        return $this;
    }

    /**
     * Sets pin field.
     *
     * @param string|null $value
     */
    public function pin(?string $value): self
    {
        $this->instance->setPin($value);
        return $this;
    }

    /**
     * Sets meeting Code field.
     *
     * @param string|null $value
     */
    public function meetingCode(?string $value): self
    {
        $this->instance->setMeetingCode($value);
        return $this;
    }

    /**
     * Sets password field.
     *
     * @param string|null $value
     */
    public function password(?string $value): self
    {
        $this->instance->setPassword($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Conference Entry Point object.
     */
    public function build(): ConferenceEntryPoint
    {
        return CoreHelper::clone($this->instance);
    }
}
