<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models\Builders;

use CalendarApiLib\Models\ConferenceSolution;
use CalendarApiLib\Models\ConferenceSolutionKey;
use Core\Utils\CoreHelper;

/**
 * Builder for model ConferenceSolution
 *
 * @see ConferenceSolution
 */
class ConferenceSolutionBuilder
{
    /**
     * @var ConferenceSolution
     */
    private $instance;

    private function __construct(ConferenceSolution $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Conference Solution Builder object.
     */
    public static function init(): self
    {
        return new self(new ConferenceSolution());
    }

    /**
     * Sets key field.
     *
     * @param ConferenceSolutionKey|null $value
     */
    public function key(?ConferenceSolutionKey $value): self
    {
        $this->instance->setKey($value);
        return $this;
    }

    /**
     * Sets name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets icon Uri field.
     *
     * @param string|null $value
     */
    public function iconUri(?string $value): self
    {
        $this->instance->setIconUri($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Conference Solution object.
     */
    public function build(): ConferenceSolution
    {
        return CoreHelper::clone($this->instance);
    }
}
