<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models\Builders;

use CalendarApiLib\Models\CustomLocation;
use Core\Utils\CoreHelper;

/**
 * Builder for model CustomLocation
 *
 * @see CustomLocation
 */
class CustomLocationBuilder
{
    /**
     * @var CustomLocation
     */
    private $instance;

    private function __construct(CustomLocation $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Custom Location Builder object.
     */
    public static function init(): self
    {
        return new self(new CustomLocation());
    }

    /**
     * Sets label field.
     *
     * @param string|null $value
     */
    public function label(?string $value): self
    {
        $this->instance->setLabel($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Custom Location object.
     */
    public function build(): CustomLocation
    {
        return CoreHelper::clone($this->instance);
    }
}
