<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models\Builders;

use CalendarApiLib\Models\ErrorResponseErrorErrorsItems;
use Core\Utils\CoreHelper;

/**
 * Builder for model ErrorResponseErrorErrorsItems
 *
 * @see ErrorResponseErrorErrorsItems
 */
class ErrorResponseErrorErrorsItemsBuilder
{
    /**
     * @var ErrorResponseErrorErrorsItems
     */
    private $instance;

    private function __construct(ErrorResponseErrorErrorsItems $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Error Response Error Errors Items Builder object.
     */
    public static function init(): self
    {
        return new self(new ErrorResponseErrorErrorsItems());
    }

    /**
     * Sets domain field.
     *
     * @param string|null $value
     */
    public function domain(?string $value): self
    {
        $this->instance->setDomain($value);
        return $this;
    }

    /**
     * Sets reason field.
     *
     * @param string|null $value
     */
    public function reason(?string $value): self
    {
        $this->instance->setReason($value);
        return $this;
    }

    /**
     * Sets message field.
     *
     * @param string|null $value
     */
    public function message(?string $value): self
    {
        $this->instance->setMessage($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Error Response Error Errors Items object.
     */
    public function build(): ErrorResponseErrorErrorsItems
    {
        return CoreHelper::clone($this->instance);
    }
}
