<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models\Builders;

use CalendarApiLib\Models\ErrorResponseError;
use CalendarApiLib\Models\ErrorResponseErrorErrorsItems;
use Core\Utils\CoreHelper;

/**
 * Builder for model ErrorResponseError
 *
 * @see ErrorResponseError
 */
class ErrorResponseErrorBuilder
{
    /**
     * @var ErrorResponseError
     */
    private $instance;

    private function __construct(ErrorResponseError $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Error Response Error Builder object.
     */
    public static function init(): self
    {
        return new self(new ErrorResponseError());
    }

    /**
     * Sets code field.
     *
     * @param int|null $value
     */
    public function code(?int $value): self
    {
        $this->instance->setCode($value);
        return $this;
    }

    /**
     * Sets message field.
     *
     * @param string|null $value
     */
    public function message(?string $value): self
    {
        $this->instance->setMessage($value);
        return $this;
    }

    /**
     * Sets errors field.
     *
     * @param ErrorResponseErrorErrorsItems[]|null $value
     */
    public function errors(?array $value): self
    {
        $this->instance->setErrors($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Error Response Error object.
     */
    public function build(): ErrorResponseError
    {
        return CoreHelper::clone($this->instance);
    }
}
