<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models\Builders;

use CalendarApiLib\Models\ErrorResponse;
use CalendarApiLib\Models\ErrorResponseError;
use Core\Utils\CoreHelper;

/**
 * Builder for model ErrorResponse
 *
 * @see ErrorResponse
 */
class ErrorResponseBuilder
{
    /**
     * @var ErrorResponse
     */
    private $instance;

    private function __construct(ErrorResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Error Response Builder object.
     */
    public static function init(): self
    {
        return new self(new ErrorResponse());
    }

    /**
     * Sets error field.
     *
     * @param ErrorResponseError|null $value
     */
    public function error(?ErrorResponseError $value): self
    {
        $this->instance->setError($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Error Response object.
     */
    public function build(): ErrorResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
