<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models\Builders;

use CalendarApiLib\Models\Attachment;
use CalendarApiLib\Models\Attendee;
use CalendarApiLib\Models\BirthdayProperties;
use CalendarApiLib\Models\ConferenceData;
use CalendarApiLib\Models\Event;
use CalendarApiLib\Models\EventDateTime;
use CalendarApiLib\Models\EventReminders;
use CalendarApiLib\Models\EventSource;
use CalendarApiLib\Models\ExtendedProperties;
use CalendarApiLib\Models\FocusTimeProperties;
use CalendarApiLib\Models\OutOfOfficeProperties;
use CalendarApiLib\Models\Person;
use CalendarApiLib\Models\WorkingLocationProperties;
use Core\Utils\CoreHelper;

/**
 * Builder for model Event
 *
 * @see Event
 */
class EventBuilder
{
    /**
     * @var Event
     */
    private $instance;

    private function __construct(Event $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Event Builder object.
     *
     * @param EventDateTime $start
     * @param EventDateTime $end
     */
    public static function init(EventDateTime $start, EventDateTime $end): self
    {
        return new self(new Event($start, $end));
    }

    /**
     * Sets kind field.
     *
     * @param string|null $value
     */
    public function kind(?string $value): self
    {
        $this->instance->setKind($value);
        return $this;
    }

    /**
     * Sets etag field.
     *
     * @param string|null $value
     */
    public function etag(?string $value): self
    {
        $this->instance->setEtag($value);
        return $this;
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets status field.
     *
     * @param string|null $value
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Sets html Link field.
     *
     * @param string|null $value
     */
    public function htmlLink(?string $value): self
    {
        $this->instance->setHtmlLink($value);
        return $this;
    }

    /**
     * Sets created field.
     *
     * @param \DateTime|null $value
     */
    public function created(?\DateTime $value): self
    {
        $this->instance->setCreated($value);
        return $this;
    }

    /**
     * Sets updated field.
     *
     * @param \DateTime|null $value
     */
    public function updated(?\DateTime $value): self
    {
        $this->instance->setUpdated($value);
        return $this;
    }

    /**
     * Sets summary field.
     *
     * @param string|null $value
     */
    public function summary(?string $value): self
    {
        $this->instance->setSummary($value);
        return $this;
    }

    /**
     * Sets description field.
     *
     * @param string|null $value
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Sets location field.
     *
     * @param string|null $value
     */
    public function location(?string $value): self
    {
        $this->instance->setLocation($value);
        return $this;
    }

    /**
     * Sets color Id field.
     *
     * @param string|null $value
     */
    public function colorId(?string $value): self
    {
        $this->instance->setColorId($value);
        return $this;
    }

    /**
     * Sets creator field.
     *
     * @param Person|null $value
     */
    public function creator(?Person $value): self
    {
        $this->instance->setCreator($value);
        return $this;
    }

    /**
     * Sets organizer field.
     *
     * @param Person|null $value
     */
    public function organizer(?Person $value): self
    {
        $this->instance->setOrganizer($value);
        return $this;
    }

    /**
     * Sets end Time Unspecified field.
     *
     * @param bool|null $value
     */
    public function endTimeUnspecified(?bool $value): self
    {
        $this->instance->setEndTimeUnspecified($value);
        return $this;
    }

    /**
     * Sets recurrence field.
     *
     * @param string[]|null $value
     */
    public function recurrence(?array $value): self
    {
        $this->instance->setRecurrence($value);
        return $this;
    }

    /**
     * Sets recurring Event Id field.
     *
     * @param string|null $value
     */
    public function recurringEventId(?string $value): self
    {
        $this->instance->setRecurringEventId($value);
        return $this;
    }

    /**
     * Sets original Start Time field.
     *
     * @param EventDateTime|null $value
     */
    public function originalStartTime(?EventDateTime $value): self
    {
        $this->instance->setOriginalStartTime($value);
        return $this;
    }

    /**
     * Sets transparency field.
     *
     * @param string|null $value
     */
    public function transparency(?string $value): self
    {
        $this->instance->setTransparency($value);
        return $this;
    }

    /**
     * Sets visibility field.
     *
     * @param string|null $value
     */
    public function visibility(?string $value): self
    {
        $this->instance->setVisibility($value);
        return $this;
    }

    /**
     * Sets i Cal UID field.
     *
     * @param string|null $value
     */
    public function iCalUid(?string $value): self
    {
        $this->instance->setICalUid($value);
        return $this;
    }

    /**
     * Sets sequence field.
     *
     * @param int|null $value
     */
    public function sequence(?int $value): self
    {
        $this->instance->setSequence($value);
        return $this;
    }

    /**
     * Sets attendees field.
     *
     * @param Attendee[]|null $value
     */
    public function attendees(?array $value): self
    {
        $this->instance->setAttendees($value);
        return $this;
    }

    /**
     * Sets attendees Omitted field.
     *
     * @param bool|null $value
     */
    public function attendeesOmitted(?bool $value): self
    {
        $this->instance->setAttendeesOmitted($value);
        return $this;
    }

    /**
     * Sets hangout Link field.
     *
     * @param string|null $value
     */
    public function hangoutLink(?string $value): self
    {
        $this->instance->setHangoutLink($value);
        return $this;
    }

    /**
     * Sets conference Data field.
     *
     * @param ConferenceData|null $value
     */
    public function conferenceData(?ConferenceData $value): self
    {
        $this->instance->setConferenceData($value);
        return $this;
    }

    /**
     * Sets guests Can Invite Others field.
     *
     * @param bool|null $value
     */
    public function guestsCanInviteOthers(?bool $value): self
    {
        $this->instance->setGuestsCanInviteOthers($value);
        return $this;
    }

    /**
     * Sets guests Can Modify field.
     *
     * @param bool|null $value
     */
    public function guestsCanModify(?bool $value): self
    {
        $this->instance->setGuestsCanModify($value);
        return $this;
    }

    /**
     * Sets guests Can See Other Guests field.
     *
     * @param bool|null $value
     */
    public function guestsCanSeeOtherGuests(?bool $value): self
    {
        $this->instance->setGuestsCanSeeOtherGuests($value);
        return $this;
    }

    /**
     * Sets private Copy field.
     *
     * @param bool|null $value
     */
    public function privateCopy(?bool $value): self
    {
        $this->instance->setPrivateCopy($value);
        return $this;
    }

    /**
     * Sets locked field.
     *
     * @param bool|null $value
     */
    public function locked(?bool $value): self
    {
        $this->instance->setLocked($value);
        return $this;
    }

    /**
     * Sets reminders field.
     *
     * @param EventReminders|null $value
     */
    public function reminders(?EventReminders $value): self
    {
        $this->instance->setReminders($value);
        return $this;
    }

    /**
     * Sets source field.
     *
     * @param EventSource|null $value
     */
    public function source(?EventSource $value): self
    {
        $this->instance->setSource($value);
        return $this;
    }

    /**
     * Sets event Type field.
     *
     * @param string|null $value
     */
    public function eventType(?string $value): self
    {
        $this->instance->setEventType($value);
        return $this;
    }

    /**
     * Sets extended Properties field.
     *
     * @param ExtendedProperties|null $value
     */
    public function extendedProperties(?ExtendedProperties $value): self
    {
        $this->instance->setExtendedProperties($value);
        return $this;
    }

    /**
     * Sets attachments field.
     *
     * @param Attachment[]|null $value
     */
    public function attachments(?array $value): self
    {
        $this->instance->setAttachments($value);
        return $this;
    }

    /**
     * Sets birthday Properties field.
     *
     * @param BirthdayProperties|null $value
     */
    public function birthdayProperties(?BirthdayProperties $value): self
    {
        $this->instance->setBirthdayProperties($value);
        return $this;
    }

    /**
     * Sets out Of Office Properties field.
     *
     * @param OutOfOfficeProperties|null $value
     */
    public function outOfOfficeProperties(?OutOfOfficeProperties $value): self
    {
        $this->instance->setOutOfOfficeProperties($value);
        return $this;
    }

    /**
     * Sets focus Time Properties field.
     *
     * @param FocusTimeProperties|null $value
     */
    public function focusTimeProperties(?FocusTimeProperties $value): self
    {
        $this->instance->setFocusTimeProperties($value);
        return $this;
    }

    /**
     * Sets working Location Properties field.
     *
     * @param WorkingLocationProperties|null $value
     */
    public function workingLocationProperties(?WorkingLocationProperties $value): self
    {
        $this->instance->setWorkingLocationProperties($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Event object.
     */
    public function build(): Event
    {
        return CoreHelper::clone($this->instance);
    }
}
