<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models\Builders;

use CalendarApiLib\Models\EventReminders;
use CalendarApiLib\Models\Reminder;
use Core\Utils\CoreHelper;

/**
 * Builder for model EventReminders
 *
 * @see EventReminders
 */
class EventRemindersBuilder
{
    /**
     * @var EventReminders
     */
    private $instance;

    private function __construct(EventReminders $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Event Reminders Builder object.
     */
    public static function init(): self
    {
        return new self(new EventReminders());
    }

    /**
     * Sets use Default field.
     *
     * @param bool|null $value
     */
    public function useDefault(?bool $value): self
    {
        $this->instance->setUseDefault($value);
        return $this;
    }

    /**
     * Sets overrides field.
     *
     * @param Reminder[]|null $value
     */
    public function overrides(?array $value): self
    {
        $this->instance->setOverrides($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Event Reminders object.
     */
    public function build(): EventReminders
    {
        return CoreHelper::clone($this->instance);
    }
}
