<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models\Builders;

use CalendarApiLib\Models\Event;
use CalendarApiLib\Models\EventList;
use CalendarApiLib\Models\Reminder;
use Core\Utils\CoreHelper;

/**
 * Builder for model EventList
 *
 * @see EventList
 */
class EventListBuilder
{
    /**
     * @var EventList
     */
    private $instance;

    private function __construct(EventList $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Event List Builder object.
     */
    public static function init(): self
    {
        return new self(new EventList());
    }

    /**
     * Sets kind field.
     *
     * @param string|null $value
     */
    public function kind(?string $value): self
    {
        $this->instance->setKind($value);
        return $this;
    }

    /**
     * Sets etag field.
     *
     * @param string|null $value
     */
    public function etag(?string $value): self
    {
        $this->instance->setEtag($value);
        return $this;
    }

    /**
     * Sets summary field.
     *
     * @param string|null $value
     */
    public function summary(?string $value): self
    {
        $this->instance->setSummary($value);
        return $this;
    }

    /**
     * Sets description field.
     *
     * @param string|null $value
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Sets updated field.
     *
     * @param \DateTime|null $value
     */
    public function updated(?\DateTime $value): self
    {
        $this->instance->setUpdated($value);
        return $this;
    }

    /**
     * Sets time Zone field.
     *
     * @param string|null $value
     */
    public function timeZone(?string $value): self
    {
        $this->instance->setTimeZone($value);
        return $this;
    }

    /**
     * Sets access Role field.
     *
     * @param string|null $value
     */
    public function accessRole(?string $value): self
    {
        $this->instance->setAccessRole($value);
        return $this;
    }

    /**
     * Sets default Reminders field.
     *
     * @param Reminder[]|null $value
     */
    public function defaultReminders(?array $value): self
    {
        $this->instance->setDefaultReminders($value);
        return $this;
    }

    /**
     * Sets next Page Token field.
     *
     * @param string|null $value
     */
    public function nextPageToken(?string $value): self
    {
        $this->instance->setNextPageToken($value);
        return $this;
    }

    /**
     * Sets next Sync Token field.
     *
     * @param string|null $value
     */
    public function nextSyncToken(?string $value): self
    {
        $this->instance->setNextSyncToken($value);
        return $this;
    }

    /**
     * Sets items field.
     *
     * @param Event[]|null $value
     */
    public function items(?array $value): self
    {
        $this->instance->setItems($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Event List object.
     */
    public function build(): EventList
    {
        return CoreHelper::clone($this->instance);
    }
}
