<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models\Builders;

use CalendarApiLib\Models\EventSource;
use Core\Utils\CoreHelper;

/**
 * Builder for model EventSource
 *
 * @see EventSource
 */
class EventSourceBuilder
{
    /**
     * @var EventSource
     */
    private $instance;

    private function __construct(EventSource $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Event Source Builder object.
     */
    public static function init(): self
    {
        return new self(new EventSource());
    }

    /**
     * Sets url field.
     *
     * @param string|null $value
     */
    public function url(?string $value): self
    {
        $this->instance->setUrl($value);
        return $this;
    }

    /**
     * Sets title field.
     *
     * @param string|null $value
     */
    public function title(?string $value): self
    {
        $this->instance->setTitle($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Event Source object.
     */
    public function build(): EventSource
    {
        return CoreHelper::clone($this->instance);
    }
}
