<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models\Builders;

use CalendarApiLib\Models\EventDateTime;
use Core\Utils\CoreHelper;

/**
 * Builder for model EventDateTime
 *
 * @see EventDateTime
 */
class EventDateTimeBuilder
{
    /**
     * @var EventDateTime
     */
    private $instance;

    private function __construct(EventDateTime $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Event Date Time Builder object.
     */
    public static function init(): self
    {
        return new self(new EventDateTime());
    }

    /**
     * Sets date field.
     *
     * @param \DateTime|null $value
     */
    public function date(?\DateTime $value): self
    {
        $this->instance->setDate($value);
        return $this;
    }

    /**
     * Sets date Time field.
     *
     * @param \DateTime|null $value
     */
    public function dateTime(?\DateTime $value): self
    {
        $this->instance->setDateTime($value);
        return $this;
    }

    /**
     * Sets time Zone field.
     *
     * @param string|null $value
     */
    public function timeZone(?string $value): self
    {
        $this->instance->setTimeZone($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Event Date Time object.
     */
    public function build(): EventDateTime
    {
        return CoreHelper::clone($this->instance);
    }
}
