<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models\Builders;

use CalendarApiLib\Models\ExtendedProperties;
use Core\Utils\CoreHelper;

/**
 * Builder for model ExtendedProperties
 *
 * @see ExtendedProperties
 */
class ExtendedPropertiesBuilder
{
    /**
     * @var ExtendedProperties
     */
    private $instance;

    private function __construct(ExtendedProperties $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Extended Properties Builder object.
     */
    public static function init(): self
    {
        return new self(new ExtendedProperties());
    }

    /**
     * Sets private field.
     *
     * @param array<string,string>|null $value
     */
    public function private(?array $value): self
    {
        $this->instance->setPrivate($value);
        return $this;
    }

    /**
     * Sets shared field.
     *
     * @param array<string,string>|null $value
     */
    public function shared(?array $value): self
    {
        $this->instance->setShared($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Extended Properties object.
     */
    public function build(): ExtendedProperties
    {
        return CoreHelper::clone($this->instance);
    }
}
