<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models\Builders;

use CalendarApiLib\Models\FocusTimeProperties;
use Core\Utils\CoreHelper;

/**
 * Builder for model FocusTimeProperties
 *
 * @see FocusTimeProperties
 */
class FocusTimePropertiesBuilder
{
    /**
     * @var FocusTimeProperties
     */
    private $instance;

    private function __construct(FocusTimeProperties $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Focus Time Properties Builder object.
     */
    public static function init(): self
    {
        return new self(new FocusTimeProperties());
    }

    /**
     * Sets auto Decline Mode field.
     *
     * @param string|null $value
     */
    public function autoDeclineMode(?string $value): self
    {
        $this->instance->setAutoDeclineMode($value);
        return $this;
    }

    /**
     * Sets decline Message field.
     *
     * @param string|null $value
     */
    public function declineMessage(?string $value): self
    {
        $this->instance->setDeclineMessage($value);
        return $this;
    }

    /**
     * Sets chat Status field.
     *
     * @param string|null $value
     */
    public function chatStatus(?string $value): self
    {
        $this->instance->setChatStatus($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Focus Time Properties object.
     */
    public function build(): FocusTimeProperties
    {
        return CoreHelper::clone($this->instance);
    }
}
