<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models\Builders;

use CalendarApiLib\Models\FreeBusyCalendar;
use CalendarApiLib\Models\FreeBusyGroup;
use CalendarApiLib\Models\FreeBusyResponse;
use Core\Utils\CoreHelper;

/**
 * Builder for model FreeBusyResponse
 *
 * @see FreeBusyResponse
 */
class FreeBusyResponseBuilder
{
    /**
     * @var FreeBusyResponse
     */
    private $instance;

    private function __construct(FreeBusyResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Free Busy Response Builder object.
     */
    public static function init(): self
    {
        return new self(new FreeBusyResponse());
    }

    /**
     * Sets kind field.
     *
     * @param string|null $value
     */
    public function kind(?string $value): self
    {
        $this->instance->setKind($value);
        return $this;
    }

    /**
     * Sets time Min field.
     *
     * @param \DateTime|null $value
     */
    public function timeMin(?\DateTime $value): self
    {
        $this->instance->setTimeMin($value);
        return $this;
    }

    /**
     * Sets time Max field.
     *
     * @param \DateTime|null $value
     */
    public function timeMax(?\DateTime $value): self
    {
        $this->instance->setTimeMax($value);
        return $this;
    }

    /**
     * Sets calendars field.
     *
     * @param array<string,FreeBusyCalendar>|null $value
     */
    public function calendars(?array $value): self
    {
        $this->instance->setCalendars($value);
        return $this;
    }

    /**
     * Sets groups field.
     *
     * @param array<string,FreeBusyGroup>|null $value
     */
    public function groups(?array $value): self
    {
        $this->instance->setGroups($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Free Busy Response object.
     */
    public function build(): FreeBusyResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
