<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models\Builders;

use CalendarApiLib\Models\FreeBusyRequest;
use CalendarApiLib\Models\FreeBusyRequestItem;
use Core\Utils\CoreHelper;

/**
 * Builder for model FreeBusyRequest
 *
 * @see FreeBusyRequest
 */
class FreeBusyRequestBuilder
{
    /**
     * @var FreeBusyRequest
     */
    private $instance;

    private function __construct(FreeBusyRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Free Busy Request Builder object.
     *
     * @param \DateTime $timeMin
     * @param \DateTime $timeMax
     * @param FreeBusyRequestItem[] $items
     */
    public static function init(\DateTime $timeMin, \DateTime $timeMax, array $items): self
    {
        return new self(new FreeBusyRequest($timeMin, $timeMax, $items));
    }

    /**
     * Sets time Zone field.
     *
     * @param string|null $value
     */
    public function timeZone(?string $value): self
    {
        $this->instance->setTimeZone($value);
        return $this;
    }

    /**
     * Sets group Expansion Max field.
     *
     * @param int|null $value
     */
    public function groupExpansionMax(?int $value): self
    {
        $this->instance->setGroupExpansionMax($value);
        return $this;
    }

    /**
     * Sets calendar Expansion Max field.
     *
     * @param int|null $value
     */
    public function calendarExpansionMax(?int $value): self
    {
        $this->instance->setCalendarExpansionMax($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Free Busy Request object.
     */
    public function build(): FreeBusyRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
