<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models\Builders;

use CalendarApiLib\Models\FreeBusyError;
use CalendarApiLib\Models\FreeBusyGroup;
use Core\Utils\CoreHelper;

/**
 * Builder for model FreeBusyGroup
 *
 * @see FreeBusyGroup
 */
class FreeBusyGroupBuilder
{
    /**
     * @var FreeBusyGroup
     */
    private $instance;

    private function __construct(FreeBusyGroup $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Free Busy Group Builder object.
     */
    public static function init(): self
    {
        return new self(new FreeBusyGroup());
    }

    /**
     * Sets calendars field.
     *
     * @param string[]|null $value
     */
    public function calendars(?array $value): self
    {
        $this->instance->setCalendars($value);
        return $this;
    }

    /**
     * Sets errors field.
     *
     * @param FreeBusyError[]|null $value
     */
    public function errors(?array $value): self
    {
        $this->instance->setErrors($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Free Busy Group object.
     */
    public function build(): FreeBusyGroup
    {
        return CoreHelper::clone($this->instance);
    }
}
