<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models\Builders;

use CalendarApiLib\Models\FreeBusyError;
use Core\Utils\CoreHelper;

/**
 * Builder for model FreeBusyError
 *
 * @see FreeBusyError
 */
class FreeBusyErrorBuilder
{
    /**
     * @var FreeBusyError
     */
    private $instance;

    private function __construct(FreeBusyError $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Free Busy Error Builder object.
     */
    public static function init(): self
    {
        return new self(new FreeBusyError());
    }

    /**
     * Sets domain field.
     *
     * @param string|null $value
     */
    public function domain(?string $value): self
    {
        $this->instance->setDomain($value);
        return $this;
    }

    /**
     * Sets reason field.
     *
     * @param string|null $value
     */
    public function reason(?string $value): self
    {
        $this->instance->setReason($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Free Busy Error object.
     */
    public function build(): FreeBusyError
    {
        return CoreHelper::clone($this->instance);
    }
}
