<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models\Builders;

use CalendarApiLib\Models\FreeBusyCalendar;
use CalendarApiLib\Models\FreeBusyError;
use CalendarApiLib\Models\TimePeriod;
use Core\Utils\CoreHelper;

/**
 * Builder for model FreeBusyCalendar
 *
 * @see FreeBusyCalendar
 */
class FreeBusyCalendarBuilder
{
    /**
     * @var FreeBusyCalendar
     */
    private $instance;

    private function __construct(FreeBusyCalendar $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Free Busy Calendar Builder object.
     */
    public static function init(): self
    {
        return new self(new FreeBusyCalendar());
    }

    /**
     * Sets busy field.
     *
     * @param TimePeriod[]|null $value
     */
    public function busy(?array $value): self
    {
        $this->instance->setBusy($value);
        return $this;
    }

    /**
     * Sets errors field.
     *
     * @param FreeBusyError[]|null $value
     */
    public function errors(?array $value): self
    {
        $this->instance->setErrors($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Free Busy Calendar object.
     */
    public function build(): FreeBusyCalendar
    {
        return CoreHelper::clone($this->instance);
    }
}
