<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models\Builders;

use CalendarApiLib\Models\FreeBusyRequestItem;
use Core\Utils\CoreHelper;

/**
 * Builder for model FreeBusyRequestItem
 *
 * @see FreeBusyRequestItem
 */
class FreeBusyRequestItemBuilder
{
    /**
     * @var FreeBusyRequestItem
     */
    private $instance;

    private function __construct(FreeBusyRequestItem $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Free Busy Request Item Builder object.
     *
     * @param string $id
     */
    public static function init(string $id): self
    {
        return new self(new FreeBusyRequestItem($id));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Free Busy Request Item object.
     */
    public function build(): FreeBusyRequestItem
    {
        return CoreHelper::clone($this->instance);
    }
}
