<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models\Builders;

use CalendarApiLib\Models\OfficeLocation;
use Core\Utils\CoreHelper;

/**
 * Builder for model OfficeLocation
 *
 * @see OfficeLocation
 */
class OfficeLocationBuilder
{
    /**
     * @var OfficeLocation
     */
    private $instance;

    private function __construct(OfficeLocation $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Office Location Builder object.
     */
    public static function init(): self
    {
        return new self(new OfficeLocation());
    }

    /**
     * Sets building Id field.
     *
     * @param string|null $value
     */
    public function buildingId(?string $value): self
    {
        $this->instance->setBuildingId($value);
        return $this;
    }

    /**
     * Sets floor Id field.
     *
     * @param string|null $value
     */
    public function floorId(?string $value): self
    {
        $this->instance->setFloorId($value);
        return $this;
    }

    /**
     * Sets floor Section Id field.
     *
     * @param string|null $value
     */
    public function floorSectionId(?string $value): self
    {
        $this->instance->setFloorSectionId($value);
        return $this;
    }

    /**
     * Sets desk Id field.
     *
     * @param string|null $value
     */
    public function deskId(?string $value): self
    {
        $this->instance->setDeskId($value);
        return $this;
    }

    /**
     * Sets label field.
     *
     * @param string|null $value
     */
    public function label(?string $value): self
    {
        $this->instance->setLabel($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Office Location object.
     */
    public function build(): OfficeLocation
    {
        return CoreHelper::clone($this->instance);
    }
}
