<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models\Builders;

use CalendarApiLib\Models\OutOfOfficeProperties;
use Core\Utils\CoreHelper;

/**
 * Builder for model OutOfOfficeProperties
 *
 * @see OutOfOfficeProperties
 */
class OutOfOfficePropertiesBuilder
{
    /**
     * @var OutOfOfficeProperties
     */
    private $instance;

    private function __construct(OutOfOfficeProperties $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Out Of Office Properties Builder object.
     */
    public static function init(): self
    {
        return new self(new OutOfOfficeProperties());
    }

    /**
     * Sets auto Decline Mode field.
     *
     * @param string|null $value
     */
    public function autoDeclineMode(?string $value): self
    {
        $this->instance->setAutoDeclineMode($value);
        return $this;
    }

    /**
     * Sets decline Message field.
     *
     * @param string|null $value
     */
    public function declineMessage(?string $value): self
    {
        $this->instance->setDeclineMessage($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Out Of Office Properties object.
     */
    public function build(): OutOfOfficeProperties
    {
        return CoreHelper::clone($this->instance);
    }
}
