<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models\Builders;

use CalendarApiLib\Models\Person;
use Core\Utils\CoreHelper;

/**
 * Builder for model Person
 *
 * @see Person
 */
class PersonBuilder
{
    /**
     * @var Person
     */
    private $instance;

    private function __construct(Person $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Person Builder object.
     */
    public static function init(): self
    {
        return new self(new Person());
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets email field.
     *
     * @param string|null $value
     */
    public function email(?string $value): self
    {
        $this->instance->setEmail($value);
        return $this;
    }

    /**
     * Sets display Name field.
     *
     * @param string|null $value
     */
    public function displayName(?string $value): self
    {
        $this->instance->setDisplayName($value);
        return $this;
    }

    /**
     * Sets self field.
     *
     * @param bool|null $value
     */
    public function self(?bool $value): self
    {
        $this->instance->setSelf($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Person object.
     */
    public function build(): Person
    {
        return CoreHelper::clone($this->instance);
    }
}
