<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models\Builders;

use CalendarApiLib\Models\Reminder;
use Core\Utils\CoreHelper;

/**
 * Builder for model Reminder
 *
 * @see Reminder
 */
class ReminderBuilder
{
    /**
     * @var Reminder
     */
    private $instance;

    private function __construct(Reminder $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Reminder Builder object.
     *
     * @param string $method
     * @param int $minutes
     */
    public static function init(string $method, int $minutes): self
    {
        return new self(new Reminder($method, $minutes));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Reminder object.
     */
    public function build(): Reminder
    {
        return CoreHelper::clone($this->instance);
    }
}
