<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models\Builders;

use CalendarApiLib\Models\StopChannelRequest;
use Core\Utils\CoreHelper;

/**
 * Builder for model StopChannelRequest
 *
 * @see StopChannelRequest
 */
class StopChannelRequestBuilder
{
    /**
     * @var StopChannelRequest
     */
    private $instance;

    private function __construct(StopChannelRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Stop Channel Request Builder object.
     *
     * @param string $id
     * @param string $resourceId
     */
    public static function init(string $id, string $resourceId): self
    {
        return new self(new StopChannelRequest($id, $resourceId));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Stop Channel Request object.
     */
    public function build(): StopChannelRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
