<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models\Builders;

use CalendarApiLib\Models\TimePeriod;
use Core\Utils\CoreHelper;

/**
 * Builder for model TimePeriod
 *
 * @see TimePeriod
 */
class TimePeriodBuilder
{
    /**
     * @var TimePeriod
     */
    private $instance;

    private function __construct(TimePeriod $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Time Period Builder object.
     */
    public static function init(): self
    {
        return new self(new TimePeriod());
    }

    /**
     * Sets start field.
     *
     * @param \DateTime|null $value
     */
    public function start(?\DateTime $value): self
    {
        $this->instance->setStart($value);
        return $this;
    }

    /**
     * Sets end field.
     *
     * @param \DateTime|null $value
     */
    public function end(?\DateTime $value): self
    {
        $this->instance->setEnd($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Time Period object.
     */
    public function build(): TimePeriod
    {
        return CoreHelper::clone($this->instance);
    }
}
