<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models\Builders;

use CalendarApiLib\Models\ChannelParams;
use CalendarApiLib\Models\WatchRequest;
use Core\Utils\CoreHelper;

/**
 * Builder for model WatchRequest
 *
 * @see WatchRequest
 */
class WatchRequestBuilder
{
    /**
     * @var WatchRequest
     */
    private $instance;

    private function __construct(WatchRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Watch Request Builder object.
     *
     * @param string $id
     * @param string $type
     * @param string $address
     */
    public static function init(string $id, string $type, string $address): self
    {
        return new self(new WatchRequest($id, $type, $address));
    }

    /**
     * Sets token field.
     *
     * @param string|null $value
     */
    public function token(?string $value): self
    {
        $this->instance->setToken($value);
        return $this;
    }

    /**
     * Sets params field.
     *
     * @param ChannelParams|null $value
     */
    public function params(?ChannelParams $value): self
    {
        $this->instance->setParams($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Watch Request object.
     */
    public function build(): WatchRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
