<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models\Builders;

use CalendarApiLib\Models\CustomLocation;
use CalendarApiLib\Models\OfficeLocation;
use CalendarApiLib\Models\WorkingLocationProperties;
use Core\Utils\CoreHelper;

/**
 * Builder for model WorkingLocationProperties
 *
 * @see WorkingLocationProperties
 */
class WorkingLocationPropertiesBuilder
{
    /**
     * @var WorkingLocationProperties
     */
    private $instance;

    private function __construct(WorkingLocationProperties $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Working Location Properties Builder object.
     */
    public static function init(): self
    {
        return new self(new WorkingLocationProperties());
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets home Office field.
     *
     * @param array|null $value
     */
    public function homeOffice(?array $value): self
    {
        $this->instance->setHomeOffice($value);
        return $this;
    }

    /**
     * Sets office Location field.
     *
     * @param OfficeLocation|null $value
     */
    public function officeLocation(?OfficeLocation $value): self
    {
        $this->instance->setOfficeLocation($value);
        return $this;
    }

    /**
     * Sets custom Location field.
     *
     * @param CustomLocation|null $value
     */
    public function customLocation(?CustomLocation $value): self
    {
        $this->instance->setCustomLocation($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Working Location Properties object.
     */
    public function build(): WorkingLocationProperties
    {
        return CoreHelper::clone($this->instance);
    }
}
