<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Apis;

use CalendarApiLib\Exceptions\ErrorResponseError1Exception;
use CalendarApiLib\Http\ApiResponse;
use CalendarApiLib\Models\FreeBusyRequest;
use CalendarApiLib\Models\FreeBusyResponse;
use Core\Request\Parameters\BodyParam;
use Core\Request\Parameters\HeaderParam;
use Core\Response\Types\ErrorType;
use CoreInterfaces\Core\Request\RequestMethod;

class FreeBusyApi extends BaseApi
{
    /**
     * Returns free/busy information for a set of calendars and groups.
     *
     * @param FreeBusyRequest $body Request body for query free-busy information.
     *
     * @return ApiResponse Response from the API call
     */
    public function queryFreeBusy(FreeBusyRequest $body): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/freeBusy')
            ->auth('oauth2')
            ->parameters(HeaderParam::init('Content-Type', 'application/json'), BodyParam::init($body)->required());

        $_resHandler = $this->responseHandler()
            ->throwErrorOn(
                '400',
                ErrorType::init(
                    'Bad request — invalid parameters or request body.',
                    ErrorResponseError1Exception::class
                )
            )
            ->throwErrorOn(
                '401',
                ErrorType::init(
                    'Authentication required or credentials are invalid.',
                    ErrorResponseError1Exception::class
                )
            )
            ->type(FreeBusyResponse::class)
            ->returnApiResponse()
            ->mapErrorTypesInApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }
}
