<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Exceptions;

use CalendarApiLib\ApiHelper;

/**
 * Standard Google API error response wrapper.
 */
class ErrorResponseError1Exception
{
    /**
     * @var \CalendarApiLib\Models\ErrorResponseError|null
     */
    private $error;

    /**
     * Returns Error.
     * Error details.
     */
    public function getError(): ?\CalendarApiLib\Models\ErrorResponseError
    {
        return $this->error;
    }

    /**
     * Sets Error.
     * Error details.
     *
     * @maps error
     */
    public function setError(?\CalendarApiLib\Models\ErrorResponseError $error): void
    {
        $this->error = $error;
    }

    /**
     * Converts the ErrorResponseError1Exception object to a human-readable string representation.
     *
     * @return string The string representation of the ErrorResponseError1Exception object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ErrorResponseError1Exception',
            ['error' => $this->error, 'additionalProperties' => $this->additionalProperties]
        );
    }

    protected $propertyNames = ['error'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }
}
