<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models;

use CalendarApiLib\ApiHelper;
use stdClass;

/**
 * A file attachment for an event.
 */
class Attachment implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $fileUrl;

    /**
     * @var string|null
     */
    private $title;

    /**
     * @var string|null
     */
    private $mimeType;

    /**
     * @var string|null
     */
    private $iconLink;

    /**
     * @var string|null
     */
    private $fileId;

    /**
     * Returns File Url.
     * URL link to the attachment. Required when adding an attachment.
     */
    public function getFileUrl(): ?string
    {
        return $this->fileUrl;
    }

    /**
     * Sets File Url.
     * URL link to the attachment. Required when adding an attachment.
     *
     * @maps fileUrl
     */
    public function setFileUrl(?string $fileUrl): void
    {
        $this->fileUrl = $fileUrl;
    }

    /**
     * Returns Title.
     * Attachment title.
     */
    public function getTitle(): ?string
    {
        return $this->title;
    }

    /**
     * Sets Title.
     * Attachment title.
     *
     * @maps title
     */
    public function setTitle(?string $title): void
    {
        $this->title = $title;
    }

    /**
     * Returns Mime Type.
     * Internet media type (MIME type) of the attachment.
     */
    public function getMimeType(): ?string
    {
        return $this->mimeType;
    }

    /**
     * Sets Mime Type.
     * Internet media type (MIME type) of the attachment.
     *
     * @maps mimeType
     */
    public function setMimeType(?string $mimeType): void
    {
        $this->mimeType = $mimeType;
    }

    /**
     * Returns Icon Link.
     * URL link to the attachment's icon.
     */
    public function getIconLink(): ?string
    {
        return $this->iconLink;
    }

    /**
     * Sets Icon Link.
     * URL link to the attachment's icon.
     *
     * @maps iconLink
     */
    public function setIconLink(?string $iconLink): void
    {
        $this->iconLink = $iconLink;
    }

    /**
     * Returns File Id.
     * ID of the attached file. Only populated for Google Drive files.
     */
    public function getFileId(): ?string
    {
        return $this->fileId;
    }

    /**
     * Sets File Id.
     * ID of the attached file. Only populated for Google Drive files.
     *
     * @maps fileId
     */
    public function setFileId(?string $fileId): void
    {
        $this->fileId = $fileId;
    }

    /**
     * Converts the Attachment object to a human-readable string representation.
     *
     * @return string The string representation of the Attachment object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Attachment',
            [
                'fileUrl' => $this->fileUrl,
                'title' => $this->title,
                'mimeType' => $this->mimeType,
                'iconLink' => $this->iconLink,
                'fileId' => $this->fileId,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['fileUrl', 'title', 'mimeType', 'iconLink', 'fileId'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->fileUrl)) {
            $json['fileUrl']  = $this->fileUrl;
        }
        if (isset($this->title)) {
            $json['title']    = $this->title;
        }
        if (isset($this->mimeType)) {
            $json['mimeType'] = $this->mimeType;
        }
        if (isset($this->iconLink)) {
            $json['iconLink'] = $this->iconLink;
        }
        if (isset($this->fileId)) {
            $json['fileId']   = $this->fileId;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
