<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models;

use CalendarApiLib\ApiHelper;
use stdClass;

/**
 * An attendee of an event.
 */
class Attendee implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $id;

    /**
     * @var string|null
     */
    private $email;

    /**
     * @var string|null
     */
    private $displayName;

    /**
     * @var bool|null
     */
    private $organizer;

    /**
     * @var bool|null
     */
    private $self;

    /**
     * @var bool|null
     */
    private $resource;

    /**
     * @var bool|null
     */
    private $optional = false;

    /**
     * @var string|null
     */
    private $responseStatus;

    /**
     * @var string|null
     */
    private $comment;

    /**
     * @var int|null
     */
    private $additionalGuests = 0;

    /**
     * Returns Id.
     * The attendee's Profile ID.
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * The attendee's Profile ID.
     *
     * @maps id
     */
    public function setId(?string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Email.
     * The attendee's email address. Required when adding an attendee.
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * Sets Email.
     * The attendee's email address. Required when adding an attendee.
     *
     * @maps email
     */
    public function setEmail(?string $email): void
    {
        $this->email = $email;
    }

    /**
     * Returns Display Name.
     * The attendee's name.
     */
    public function getDisplayName(): ?string
    {
        return $this->displayName;
    }

    /**
     * Sets Display Name.
     * The attendee's name.
     *
     * @maps displayName
     */
    public function setDisplayName(?string $displayName): void
    {
        $this->displayName = $displayName;
    }

    /**
     * Returns Organizer.
     * Whether the attendee is the organizer of the event.
     */
    public function getOrganizer(): ?bool
    {
        return $this->organizer;
    }

    /**
     * Sets Organizer.
     * Whether the attendee is the organizer of the event.
     *
     * @maps organizer
     */
    public function setOrganizer(?bool $organizer): void
    {
        $this->organizer = $organizer;
    }

    /**
     * Returns Self.
     * Whether this entry represents the calendar on which this copy of the event appears.
     */
    public function getSelf(): ?bool
    {
        return $this->self;
    }

    /**
     * Sets Self.
     * Whether this entry represents the calendar on which this copy of the event appears.
     *
     * @maps self
     */
    public function setSelf(?bool $self): void
    {
        $this->self = $self;
    }

    /**
     * Returns Resource.
     * Whether the attendee is a resource (e.g. a room).
     */
    public function getResource(): ?bool
    {
        return $this->resource;
    }

    /**
     * Sets Resource.
     * Whether the attendee is a resource (e.g. a room).
     *
     * @maps resource
     */
    public function setResource(?bool $resource): void
    {
        $this->resource = $resource;
    }

    /**
     * Returns Optional.
     * Whether this is an optional attendee.
     */
    public function getOptional(): ?bool
    {
        return $this->optional;
    }

    /**
     * Sets Optional.
     * Whether this is an optional attendee.
     *
     * @maps optional
     */
    public function setOptional(?bool $optional): void
    {
        $this->optional = $optional;
    }

    /**
     * Returns Response Status.
     * The attendee's response status.
     */
    public function getResponseStatus(): ?string
    {
        return $this->responseStatus;
    }

    /**
     * Sets Response Status.
     * The attendee's response status.
     *
     * @maps responseStatus
     * @factory \CalendarApiLib\Models\ResponseStatus::checkValue
     */
    public function setResponseStatus(?string $responseStatus): void
    {
        $this->responseStatus = $responseStatus;
    }

    /**
     * Returns Comment.
     * The attendee's response comment.
     */
    public function getComment(): ?string
    {
        return $this->comment;
    }

    /**
     * Sets Comment.
     * The attendee's response comment.
     *
     * @maps comment
     */
    public function setComment(?string $comment): void
    {
        $this->comment = $comment;
    }

    /**
     * Returns Additional Guests.
     * Number of additional guests the attendee is bringing.
     */
    public function getAdditionalGuests(): ?int
    {
        return $this->additionalGuests;
    }

    /**
     * Sets Additional Guests.
     * Number of additional guests the attendee is bringing.
     *
     * @maps additionalGuests
     */
    public function setAdditionalGuests(?int $additionalGuests): void
    {
        $this->additionalGuests = $additionalGuests;
    }

    /**
     * Converts the Attendee object to a human-readable string representation.
     *
     * @return string The string representation of the Attendee object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Attendee',
            [
                'id' => $this->id,
                'email' => $this->email,
                'displayName' => $this->displayName,
                'organizer' => $this->organizer,
                'self' => $this->self,
                'resource' => $this->resource,
                'optional' => $this->optional,
                'responseStatus' => $this->responseStatus,
                'comment' => $this->comment,
                'additionalGuests' => $this->additionalGuests,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'id',
        'email',
        'displayName',
        'organizer',
        'self',
        'resource',
        'optional',
        'responseStatus',
        'comment',
        'additionalGuests'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->id)) {
            $json['id']               = $this->id;
        }
        if (isset($this->email)) {
            $json['email']            = $this->email;
        }
        if (isset($this->displayName)) {
            $json['displayName']      = $this->displayName;
        }
        if (isset($this->organizer)) {
            $json['organizer']        = $this->organizer;
        }
        if (isset($this->self)) {
            $json['self']             = $this->self;
        }
        if (isset($this->resource)) {
            $json['resource']         = $this->resource;
        }
        if (isset($this->optional)) {
            $json['optional']         = $this->optional;
        }
        if (isset($this->responseStatus)) {
            $json['responseStatus']   = ResponseStatus::checkValue($this->responseStatus);
        }
        if (isset($this->comment)) {
            $json['comment']          = $this->comment;
        }
        if (isset($this->additionalGuests)) {
            $json['additionalGuests'] = $this->additionalGuests;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
