<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * Type of birthday or special event.
 */
class BirthdayType
{
    public const ANNIVERSARY = 'anniversary';

    public const BIRTHDAY = 'birthday';

    public const CUSTOM = 'custom';

    public const OTHER = 'other';

    public const SELF_ = 'self';

    private const _ALL_VALUES = [self::ANNIVERSARY, self::BIRTHDAY, self::CUSTOM, self::OTHER, self::SELF_];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for BirthdayType.");
    }
}
