<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models;

use CalendarApiLib\ApiHelper;
use stdClass;

/**
 * Birthday or special event data. Used if eventType is birthday.
 */
class BirthdayProperties implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $contact;

    /**
     * @var string|null
     */
    private $type;

    /**
     * @var string|null
     */
    private $customTypeName;

    /**
     * Returns Contact.
     * Resource name of the contact this birthday event is linked to.
     */
    public function getContact(): ?string
    {
        return $this->contact;
    }

    /**
     * Sets Contact.
     * Resource name of the contact this birthday event is linked to.
     *
     * @maps contact
     */
    public function setContact(?string $contact): void
    {
        $this->contact = $contact;
    }

    /**
     * Returns Type.
     * Type of birthday or special event.
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * Type of birthday or special event.
     *
     * @maps type
     * @factory \CalendarApiLib\Models\BirthdayType::checkValue
     */
    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns Custom Type Name.
     * Custom type label if type is "custom".
     */
    public function getCustomTypeName(): ?string
    {
        return $this->customTypeName;
    }

    /**
     * Sets Custom Type Name.
     * Custom type label if type is "custom".
     *
     * @maps customTypeName
     */
    public function setCustomTypeName(?string $customTypeName): void
    {
        $this->customTypeName = $customTypeName;
    }

    /**
     * Converts the BirthdayProperties object to a human-readable string representation.
     *
     * @return string The string representation of the BirthdayProperties object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'BirthdayProperties',
            [
                'contact' => $this->contact,
                'type' => $this->type,
                'customTypeName' => $this->customTypeName,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['contact', 'type', 'customTypeName'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->contact)) {
            $json['contact']        = $this->contact;
        }
        if (isset($this->type)) {
            $json['type']           = BirthdayType::checkValue($this->type);
        }
        if (isset($this->customTypeName)) {
            $json['customTypeName'] = $this->customTypeName;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
