<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models;

use CalendarApiLib\ApiHelper;
use stdClass;

/**
 * The notifications the authenticated user receives for this calendar.
 */
class CalendarListEntryNotificationSettings implements \JsonSerializable
{
    /**
     * @var CalendarNotification[]|null
     */
    private $notifications;

    /**
     * Returns Notifications.
     * List of notification settings for this calendar.
     *
     * @return CalendarNotification[]|null
     */
    public function getNotifications(): ?array
    {
        return $this->notifications;
    }

    /**
     * Sets Notifications.
     * List of notification settings for this calendar.
     *
     * @maps notifications
     *
     * @param CalendarNotification[]|null $notifications
     */
    public function setNotifications(?array $notifications): void
    {
        $this->notifications = $notifications;
    }

    /**
     * Converts the CalendarListEntryNotificationSettings object to a human-readable string representation.
     *
     * @return string The string representation of the CalendarListEntryNotificationSettings object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CalendarListEntryNotificationSettings',
            ['notifications' => $this->notifications, 'additionalProperties' => $this->additionalProperties]
        );
    }

    protected $propertyNames = ['notifications'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->notifications)) {
            $json['notifications'] = $this->notifications;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
