<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models;

use CalendarApiLib\ApiHelper;
use stdClass;

/**
 * A paginated list of the user's calendar list entries.
 */
class CalendarListResponse implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $kind = 'calendar#calendarList';

    /**
     * @var string|null
     */
    private $etag;

    /**
     * @var string|null
     */
    private $nextPageToken;

    /**
     * @var string|null
     */
    private $nextSyncToken;

    /**
     * @var CalendarListEntry[]|null
     */
    private $items;

    /**
     * Returns Kind.
     * Type of the collection.
     */
    public function getKind(): ?string
    {
        return $this->kind;
    }

    /**
     * Sets Kind.
     * Type of the collection.
     *
     * @maps kind
     */
    public function setKind(?string $kind): void
    {
        $this->kind = $kind;
    }

    /**
     * Returns Etag.
     * ETag of the collection.
     */
    public function getEtag(): ?string
    {
        return $this->etag;
    }

    /**
     * Sets Etag.
     * ETag of the collection.
     *
     * @maps etag
     */
    public function setEtag(?string $etag): void
    {
        $this->etag = $etag;
    }

    /**
     * Returns Next Page Token.
     * Token used to access the next page of this result. Omitted if no further results are available.
     */
    public function getNextPageToken(): ?string
    {
        return $this->nextPageToken;
    }

    /**
     * Sets Next Page Token.
     * Token used to access the next page of this result. Omitted if no further results are available.
     *
     * @maps nextPageToken
     */
    public function setNextPageToken(?string $nextPageToken): void
    {
        $this->nextPageToken = $nextPageToken;
    }

    /**
     * Returns Next Sync Token.
     * Token used for incremental synchronization at a later point. Only provided on the last page of
     * results.
     */
    public function getNextSyncToken(): ?string
    {
        return $this->nextSyncToken;
    }

    /**
     * Sets Next Sync Token.
     * Token used for incremental synchronization at a later point. Only provided on the last page of
     * results.
     *
     * @maps nextSyncToken
     */
    public function setNextSyncToken(?string $nextSyncToken): void
    {
        $this->nextSyncToken = $nextSyncToken;
    }

    /**
     * Returns Items.
     * Calendars on the user's calendar list.
     *
     * @return CalendarListEntry[]|null
     */
    public function getItems(): ?array
    {
        return $this->items;
    }

    /**
     * Sets Items.
     * Calendars on the user's calendar list.
     *
     * @maps items
     *
     * @param CalendarListEntry[]|null $items
     */
    public function setItems(?array $items): void
    {
        $this->items = $items;
    }

    /**
     * Converts the CalendarListResponse object to a human-readable string representation.
     *
     * @return string The string representation of the CalendarListResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CalendarListResponse',
            [
                'kind' => $this->kind,
                'etag' => $this->etag,
                'nextPageToken' => $this->nextPageToken,
                'nextSyncToken' => $this->nextSyncToken,
                'items' => $this->items,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['kind', 'etag', 'nextPageToken', 'nextSyncToken', 'items'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->kind)) {
            $json['kind']          = $this->kind;
        }
        if (isset($this->etag)) {
            $json['etag']          = $this->etag;
        }
        if (isset($this->nextPageToken)) {
            $json['nextPageToken'] = $this->nextPageToken;
        }
        if (isset($this->nextSyncToken)) {
            $json['nextSyncToken'] = $this->nextSyncToken;
        }
        if (isset($this->items)) {
            $json['items']         = $this->items;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
