<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models;

use CalendarApiLib\ApiHelper;
use stdClass;

/**
 * An entry on the user's calendar list.
 */
class CalendarListEntry implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $kind = 'calendar#calendarListEntry';

    /**
     * @var string|null
     */
    private $etag;

    /**
     * @var string|null
     */
    private $id;

    /**
     * @var string|null
     */
    private $summary;

    /**
     * @var string|null
     */
    private $description;

    /**
     * @var string|null
     */
    private $location;

    /**
     * @var string|null
     */
    private $timeZone;

    /**
     * @var string|null
     */
    private $summaryOverride;

    /**
     * @var string|null
     */
    private $colorId;

    /**
     * @var string|null
     */
    private $backgroundColor;

    /**
     * @var string|null
     */
    private $foregroundColor;

    /**
     * @var bool|null
     */
    private $hidden = false;

    /**
     * @var bool|null
     */
    private $selected = false;

    /**
     * @var string|null
     */
    private $accessRole;

    /**
     * @var Reminder[]|null
     */
    private $defaultReminders;

    /**
     * @var CalendarListEntryNotificationSettings|null
     */
    private $notificationSettings;

    /**
     * @var bool|null
     */
    private $primary;

    /**
     * @var bool|null
     */
    private $deleted = false;

    /**
     * @var CalendarListEntryConferenceProperties|null
     */
    private $conferenceProperties;

    /**
     * Returns Kind.
     * Type of the resource.
     */
    public function getKind(): ?string
    {
        return $this->kind;
    }

    /**
     * Sets Kind.
     * Type of the resource.
     *
     * @maps kind
     */
    public function setKind(?string $kind): void
    {
        $this->kind = $kind;
    }

    /**
     * Returns Etag.
     * ETag of the resource.
     */
    public function getEtag(): ?string
    {
        return $this->etag;
    }

    /**
     * Sets Etag.
     * ETag of the resource.
     *
     * @maps etag
     */
    public function setEtag(?string $etag): void
    {
        $this->etag = $etag;
    }

    /**
     * Returns Id.
     * Identifier of the calendar. Use this value as the calendarId path parameter in event operations.
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * Identifier of the calendar. Use this value as the calendarId path parameter in event operations.
     *
     * @maps id
     */
    public function setId(?string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Summary.
     * Title of the calendar.
     */
    public function getSummary(): ?string
    {
        return $this->summary;
    }

    /**
     * Sets Summary.
     * Title of the calendar.
     *
     * @maps summary
     */
    public function setSummary(?string $summary): void
    {
        $this->summary = $summary;
    }

    /**
     * Returns Description.
     * Description of the calendar.
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     * Description of the calendar.
     *
     * @maps description
     */
    public function setDescription(?string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns Location.
     * Geographic location of the calendar as free-form text.
     */
    public function getLocation(): ?string
    {
        return $this->location;
    }

    /**
     * Sets Location.
     * Geographic location of the calendar as free-form text.
     *
     * @maps location
     */
    public function setLocation(?string $location): void
    {
        $this->location = $location;
    }

    /**
     * Returns Time Zone.
     * The time zone of the calendar.
     */
    public function getTimeZone(): ?string
    {
        return $this->timeZone;
    }

    /**
     * Sets Time Zone.
     * The time zone of the calendar.
     *
     * @maps timeZone
     */
    public function setTimeZone(?string $timeZone): void
    {
        $this->timeZone = $timeZone;
    }

    /**
     * Returns Summary Override.
     * The summary that the authenticated user has set for this calendar.
     */
    public function getSummaryOverride(): ?string
    {
        return $this->summaryOverride;
    }

    /**
     * Sets Summary Override.
     * The summary that the authenticated user has set for this calendar.
     *
     * @maps summaryOverride
     */
    public function setSummaryOverride(?string $summaryOverride): void
    {
        $this->summaryOverride = $summaryOverride;
    }

    /**
     * Returns Color Id.
     * The color of the calendar. References an entry in the calendar section of the colors definition.
     */
    public function getColorId(): ?string
    {
        return $this->colorId;
    }

    /**
     * Sets Color Id.
     * The color of the calendar. References an entry in the calendar section of the colors definition.
     *
     * @maps colorId
     */
    public function setColorId(?string $colorId): void
    {
        $this->colorId = $colorId;
    }

    /**
     * Returns Background Color.
     * The main color of the calendar in hexadecimal format (e.g. "#0088aa").
     */
    public function getBackgroundColor(): ?string
    {
        return $this->backgroundColor;
    }

    /**
     * Sets Background Color.
     * The main color of the calendar in hexadecimal format (e.g. "#0088aa").
     *
     * @maps backgroundColor
     */
    public function setBackgroundColor(?string $backgroundColor): void
    {
        $this->backgroundColor = $backgroundColor;
    }

    /**
     * Returns Foreground Color.
     * The foreground color of the calendar in hexadecimal format (e.g. "#ffffff").
     */
    public function getForegroundColor(): ?string
    {
        return $this->foregroundColor;
    }

    /**
     * Sets Foreground Color.
     * The foreground color of the calendar in hexadecimal format (e.g. "#ffffff").
     *
     * @maps foregroundColor
     */
    public function setForegroundColor(?string $foregroundColor): void
    {
        $this->foregroundColor = $foregroundColor;
    }

    /**
     * Returns Hidden.
     * Whether the calendar has been hidden from the list.
     */
    public function getHidden(): ?bool
    {
        return $this->hidden;
    }

    /**
     * Sets Hidden.
     * Whether the calendar has been hidden from the list.
     *
     * @maps hidden
     */
    public function setHidden(?bool $hidden): void
    {
        $this->hidden = $hidden;
    }

    /**
     * Returns Selected.
     * Whether the calendar content shows up in the calendar UI.
     */
    public function getSelected(): ?bool
    {
        return $this->selected;
    }

    /**
     * Sets Selected.
     * Whether the calendar content shows up in the calendar UI.
     *
     * @maps selected
     */
    public function setSelected(?bool $selected): void
    {
        $this->selected = $selected;
    }

    /**
     * Returns Access Role.
     * The user's access role for a calendar.
     */
    public function getAccessRole(): ?string
    {
        return $this->accessRole;
    }

    /**
     * Sets Access Role.
     * The user's access role for a calendar.
     *
     * @maps accessRole
     * @factory \CalendarApiLib\Models\CalendarAccessRole::checkValue
     */
    public function setAccessRole(?string $accessRole): void
    {
        $this->accessRole = $accessRole;
    }

    /**
     * Returns Default Reminders.
     * The default reminders that the authenticated user has for this calendar.
     *
     * @return Reminder[]|null
     */
    public function getDefaultReminders(): ?array
    {
        return $this->defaultReminders;
    }

    /**
     * Sets Default Reminders.
     * The default reminders that the authenticated user has for this calendar.
     *
     * @maps defaultReminders
     *
     * @param Reminder[]|null $defaultReminders
     */
    public function setDefaultReminders(?array $defaultReminders): void
    {
        $this->defaultReminders = $defaultReminders;
    }

    /**
     * Returns Notification Settings.
     * The notifications the authenticated user receives for this calendar.
     */
    public function getNotificationSettings(): ?CalendarListEntryNotificationSettings
    {
        return $this->notificationSettings;
    }

    /**
     * Sets Notification Settings.
     * The notifications the authenticated user receives for this calendar.
     *
     * @maps notificationSettings
     */
    public function setNotificationSettings(?CalendarListEntryNotificationSettings $notificationSettings): void
    {
        $this->notificationSettings = $notificationSettings;
    }

    /**
     * Returns Primary.
     * Whether the calendar is the primary calendar of the authenticated user.
     */
    public function getPrimary(): ?bool
    {
        return $this->primary;
    }

    /**
     * Sets Primary.
     * Whether the calendar is the primary calendar of the authenticated user.
     *
     * @maps primary
     */
    public function setPrimary(?bool $primary): void
    {
        $this->primary = $primary;
    }

    /**
     * Returns Deleted.
     * Whether the calendar list entry has been removed from the list.
     */
    public function getDeleted(): ?bool
    {
        return $this->deleted;
    }

    /**
     * Sets Deleted.
     * Whether the calendar list entry has been removed from the list.
     *
     * @maps deleted
     */
    public function setDeleted(?bool $deleted): void
    {
        $this->deleted = $deleted;
    }

    /**
     * Returns Conference Properties.
     * Conference properties for this calendar.
     */
    public function getConferenceProperties(): ?CalendarListEntryConferenceProperties
    {
        return $this->conferenceProperties;
    }

    /**
     * Sets Conference Properties.
     * Conference properties for this calendar.
     *
     * @maps conferenceProperties
     */
    public function setConferenceProperties(?CalendarListEntryConferenceProperties $conferenceProperties): void
    {
        $this->conferenceProperties = $conferenceProperties;
    }

    /**
     * Converts the CalendarListEntry object to a human-readable string representation.
     *
     * @return string The string representation of the CalendarListEntry object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CalendarListEntry',
            [
                'kind' => $this->kind,
                'etag' => $this->etag,
                'id' => $this->id,
                'summary' => $this->summary,
                'description' => $this->description,
                'location' => $this->location,
                'timeZone' => $this->timeZone,
                'summaryOverride' => $this->summaryOverride,
                'colorId' => $this->colorId,
                'backgroundColor' => $this->backgroundColor,
                'foregroundColor' => $this->foregroundColor,
                'hidden' => $this->hidden,
                'selected' => $this->selected,
                'accessRole' => $this->accessRole,
                'defaultReminders' => $this->defaultReminders,
                'notificationSettings' => $this->notificationSettings,
                'primary' => $this->primary,
                'deleted' => $this->deleted,
                'conferenceProperties' => $this->conferenceProperties,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'kind',
        'etag',
        'id',
        'summary',
        'description',
        'location',
        'timeZone',
        'summaryOverride',
        'colorId',
        'backgroundColor',
        'foregroundColor',
        'hidden',
        'selected',
        'accessRole',
        'defaultReminders',
        'notificationSettings',
        'primary',
        'deleted',
        'conferenceProperties'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->kind)) {
            $json['kind']                 = $this->kind;
        }
        if (isset($this->etag)) {
            $json['etag']                 = $this->etag;
        }
        if (isset($this->id)) {
            $json['id']                   = $this->id;
        }
        if (isset($this->summary)) {
            $json['summary']              = $this->summary;
        }
        if (isset($this->description)) {
            $json['description']          = $this->description;
        }
        if (isset($this->location)) {
            $json['location']             = $this->location;
        }
        if (isset($this->timeZone)) {
            $json['timeZone']             = $this->timeZone;
        }
        if (isset($this->summaryOverride)) {
            $json['summaryOverride']      = $this->summaryOverride;
        }
        if (isset($this->colorId)) {
            $json['colorId']              = $this->colorId;
        }
        if (isset($this->backgroundColor)) {
            $json['backgroundColor']      = $this->backgroundColor;
        }
        if (isset($this->foregroundColor)) {
            $json['foregroundColor']      = $this->foregroundColor;
        }
        if (isset($this->hidden)) {
            $json['hidden']               = $this->hidden;
        }
        if (isset($this->selected)) {
            $json['selected']             = $this->selected;
        }
        if (isset($this->accessRole)) {
            $json['accessRole']           = CalendarAccessRole::checkValue($this->accessRole);
        }
        if (isset($this->defaultReminders)) {
            $json['defaultReminders']     = $this->defaultReminders;
        }
        if (isset($this->notificationSettings)) {
            $json['notificationSettings'] = $this->notificationSettings;
        }
        if (isset($this->primary)) {
            $json['primary']              = $this->primary;
        }
        if (isset($this->deleted)) {
            $json['deleted']              = $this->deleted;
        }
        if (isset($this->conferenceProperties)) {
            $json['conferenceProperties'] = $this->conferenceProperties;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
