<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models;

use CalendarApiLib\ApiHelper;
use stdClass;

/**
 * Conference properties for this calendar.
 */
class CalendarListEntryConferenceProperties implements \JsonSerializable
{
    /**
     * @var string[]|null
     */
    private $allowedConferenceSolutionTypes;

    /**
     * Returns Allowed Conference Solution Types.
     * The types of conference solutions supported for this calendar.
     *
     * @return string[]|null
     */
    public function getAllowedConferenceSolutionTypes(): ?array
    {
        return $this->allowedConferenceSolutionTypes;
    }

    /**
     * Sets Allowed Conference Solution Types.
     * The types of conference solutions supported for this calendar.
     *
     * @maps allowedConferenceSolutionTypes
     * @factory \CalendarApiLib\Models\ConferenceSolutionType::checkValue
     *
     * @param string[]|null $allowedConferenceSolutionTypes
     */
    public function setAllowedConferenceSolutionTypes(?array $allowedConferenceSolutionTypes): void
    {
        $this->allowedConferenceSolutionTypes = $allowedConferenceSolutionTypes;
    }

    /**
     * Converts the CalendarListEntryConferenceProperties object to a human-readable string representation.
     *
     * @return string The string representation of the CalendarListEntryConferenceProperties object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CalendarListEntryConferenceProperties',
            [
                'allowedConferenceSolutionTypes' => $this->allowedConferenceSolutionTypes,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['allowedConferenceSolutionTypes'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->allowedConferenceSolutionTypes)) {
            $json['allowedConferenceSolutionTypes'] =
                ConferenceSolutionType::checkValue(
                    $this->allowedConferenceSolutionTypes
                );
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
