<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models;

use CalendarApiLib\ApiHelper;
use stdClass;

/**
 * A notification channel used to watch for resource changes.
 */
class Channel implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $kind = 'api#channel';

    /**
     * @var string|null
     */
    private $id;

    /**
     * @var string|null
     */
    private $resourceId;

    /**
     * @var string|null
     */
    private $resourceUri;

    /**
     * @var string|null
     */
    private $token;

    /**
     * @var int|null
     */
    private $expiration;

    /**
     * Returns Kind.
     * Identifies this as a notification channel used to watch for changes to a resource.
     */
    public function getKind(): ?string
    {
        return $this->kind;
    }

    /**
     * Sets Kind.
     * Identifies this as a notification channel used to watch for changes to a resource.
     *
     * @maps kind
     */
    public function setKind(?string $kind): void
    {
        $this->kind = $kind;
    }

    /**
     * Returns Id.
     * A UUID or similar unique string that identifies this channel.
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * A UUID or similar unique string that identifies this channel.
     *
     * @maps id
     */
    public function setId(?string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Resource Id.
     * An opaque value that identifies the resource being watched on this channel.
     */
    public function getResourceId(): ?string
    {
        return $this->resourceId;
    }

    /**
     * Sets Resource Id.
     * An opaque value that identifies the resource being watched on this channel.
     *
     * @maps resourceId
     */
    public function setResourceId(?string $resourceId): void
    {
        $this->resourceId = $resourceId;
    }

    /**
     * Returns Resource Uri.
     * A version-specific identifier for the watched resource.
     */
    public function getResourceUri(): ?string
    {
        return $this->resourceUri;
    }

    /**
     * Sets Resource Uri.
     * A version-specific identifier for the watched resource.
     *
     * @maps resourceUri
     */
    public function setResourceUri(?string $resourceUri): void
    {
        $this->resourceUri = $resourceUri;
    }

    /**
     * Returns Token.
     * An arbitrary string delivered to the target address with each notification.
     */
    public function getToken(): ?string
    {
        return $this->token;
    }

    /**
     * Sets Token.
     * An arbitrary string delivered to the target address with each notification.
     *
     * @maps token
     */
    public function setToken(?string $token): void
    {
        $this->token = $token;
    }

    /**
     * Returns Expiration.
     * Date and time of notification channel expiration, expressed as a Unix timestamp, in milliseconds.
     */
    public function getExpiration(): ?int
    {
        return $this->expiration;
    }

    /**
     * Sets Expiration.
     * Date and time of notification channel expiration, expressed as a Unix timestamp, in milliseconds.
     *
     * @maps expiration
     */
    public function setExpiration(?int $expiration): void
    {
        $this->expiration = $expiration;
    }

    /**
     * Converts the Channel object to a human-readable string representation.
     *
     * @return string The string representation of the Channel object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Channel',
            [
                'kind' => $this->kind,
                'id' => $this->id,
                'resourceId' => $this->resourceId,
                'resourceUri' => $this->resourceUri,
                'token' => $this->token,
                'expiration' => $this->expiration,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['kind', 'id', 'resourceId', 'resourceUri', 'token', 'expiration'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->kind)) {
            $json['kind']        = $this->kind;
        }
        if (isset($this->id)) {
            $json['id']          = $this->id;
        }
        if (isset($this->resourceId)) {
            $json['resourceId']  = $this->resourceId;
        }
        if (isset($this->resourceUri)) {
            $json['resourceUri'] = $this->resourceUri;
        }
        if (isset($this->token)) {
            $json['token']       = $this->token;
        }
        if (isset($this->expiration)) {
            $json['expiration']  = $this->expiration;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
