<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models;

use CalendarApiLib\ApiHelper;
use stdClass;

/**
 * Information about an individual conference entry point.
 */
class ConferenceEntryPoint implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $entryPointType;

    /**
     * @var string|null
     */
    private $uri;

    /**
     * @var string|null
     */
    private $label;

    /**
     * @var string|null
     */
    private $pin;

    /**
     * @var string|null
     */
    private $meetingCode;

    /**
     * @var string|null
     */
    private $password;

    /**
     * Returns Entry Point Type.
     * The type of conference entry point.
     */
    public function getEntryPointType(): ?string
    {
        return $this->entryPointType;
    }

    /**
     * Sets Entry Point Type.
     * The type of conference entry point.
     *
     * @maps entryPointType
     * @factory \CalendarApiLib\Models\EntryPointType::checkValue
     */
    public function setEntryPointType(?string $entryPointType): void
    {
        $this->entryPointType = $entryPointType;
    }

    /**
     * Returns Uri.
     * The URI of the entry point. Maximum length is 1300 characters.
     */
    public function getUri(): ?string
    {
        return $this->uri;
    }

    /**
     * Sets Uri.
     * The URI of the entry point. Maximum length is 1300 characters.
     *
     * @maps uri
     */
    public function setUri(?string $uri): void
    {
        $this->uri = $uri;
    }

    /**
     * Returns Label.
     * The label for the URI.
     */
    public function getLabel(): ?string
    {
        return $this->label;
    }

    /**
     * Sets Label.
     * The label for the URI.
     *
     * @maps label
     */
    public function setLabel(?string $label): void
    {
        $this->label = $label;
    }

    /**
     * Returns Pin.
     * The PIN to access the conference.
     */
    public function getPin(): ?string
    {
        return $this->pin;
    }

    /**
     * Sets Pin.
     * The PIN to access the conference.
     *
     * @maps pin
     */
    public function setPin(?string $pin): void
    {
        $this->pin = $pin;
    }

    /**
     * Returns Meeting Code.
     * The meeting code to access the conference.
     */
    public function getMeetingCode(): ?string
    {
        return $this->meetingCode;
    }

    /**
     * Sets Meeting Code.
     * The meeting code to access the conference.
     *
     * @maps meetingCode
     */
    public function setMeetingCode(?string $meetingCode): void
    {
        $this->meetingCode = $meetingCode;
    }

    /**
     * Returns Password.
     * The password to access the conference.
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    /**
     * Sets Password.
     * The password to access the conference.
     *
     * @maps password
     */
    public function setPassword(?string $password): void
    {
        $this->password = $password;
    }

    /**
     * Converts the ConferenceEntryPoint object to a human-readable string representation.
     *
     * @return string The string representation of the ConferenceEntryPoint object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ConferenceEntryPoint',
            [
                'entryPointType' => $this->entryPointType,
                'uri' => $this->uri,
                'label' => $this->label,
                'pin' => $this->pin,
                'meetingCode' => $this->meetingCode,
                'password' => $this->password,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['entryPointType', 'uri', 'label', 'pin', 'meetingCode', 'password'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->entryPointType)) {
            $json['entryPointType'] = EntryPointType::checkValue($this->entryPointType);
        }
        if (isset($this->uri)) {
            $json['uri']            = $this->uri;
        }
        if (isset($this->label)) {
            $json['label']          = $this->label;
        }
        if (isset($this->pin)) {
            $json['pin']            = $this->pin;
        }
        if (isset($this->meetingCode)) {
            $json['meetingCode']    = $this->meetingCode;
        }
        if (isset($this->password)) {
            $json['password']       = $this->password;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
