<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models;

use CalendarApiLib\ApiHelper;
use stdClass;

/**
 * Information about a conference (e.g. Google Meet).
 */
class ConferenceData implements \JsonSerializable
{
    /**
     * @var ConferenceCreateRequest|null
     */
    private $createRequest;

    /**
     * @var ConferenceEntryPoint[]|null
     */
    private $entryPoints;

    /**
     * @var ConferenceSolution|null
     */
    private $conferenceSolution;

    /**
     * @var string|null
     */
    private $conferenceId;

    /**
     * @var string|null
     */
    private $notes;

    /**
     * @var string|null
     */
    private $signature;

    /**
     * Returns Create Request.
     * A request to generate a new conference and attach it to the event.
     */
    public function getCreateRequest(): ?ConferenceCreateRequest
    {
        return $this->createRequest;
    }

    /**
     * Sets Create Request.
     * A request to generate a new conference and attach it to the event.
     *
     * @maps createRequest
     */
    public function setCreateRequest(?ConferenceCreateRequest $createRequest): void
    {
        $this->createRequest = $createRequest;
    }

    /**
     * Returns Entry Points.
     * Information about individual conference entry points.
     *
     * @return ConferenceEntryPoint[]|null
     */
    public function getEntryPoints(): ?array
    {
        return $this->entryPoints;
    }

    /**
     * Sets Entry Points.
     * Information about individual conference entry points.
     *
     * @maps entryPoints
     *
     * @param ConferenceEntryPoint[]|null $entryPoints
     */
    public function setEntryPoints(?array $entryPoints): void
    {
        $this->entryPoints = $entryPoints;
    }

    /**
     * Returns Conference Solution.
     * Conference solution information, such as Google Meet.
     */
    public function getConferenceSolution(): ?ConferenceSolution
    {
        return $this->conferenceSolution;
    }

    /**
     * Sets Conference Solution.
     * Conference solution information, such as Google Meet.
     *
     * @maps conferenceSolution
     */
    public function setConferenceSolution(?ConferenceSolution $conferenceSolution): void
    {
        $this->conferenceSolution = $conferenceSolution;
    }

    /**
     * Returns Conference Id.
     * The ID of the conference.
     */
    public function getConferenceId(): ?string
    {
        return $this->conferenceId;
    }

    /**
     * Sets Conference Id.
     * The ID of the conference.
     *
     * @maps conferenceId
     */
    public function setConferenceId(?string $conferenceId): void
    {
        $this->conferenceId = $conferenceId;
    }

    /**
     * Returns Notes.
     * Additional notes to display to the user. May contain HTML.
     */
    public function getNotes(): ?string
    {
        return $this->notes;
    }

    /**
     * Sets Notes.
     * Additional notes to display to the user. May contain HTML.
     *
     * @maps notes
     */
    public function setNotes(?string $notes): void
    {
        $this->notes = $notes;
    }

    /**
     * Returns Signature.
     * Server-generated signature of the conference data.
     */
    public function getSignature(): ?string
    {
        return $this->signature;
    }

    /**
     * Sets Signature.
     * Server-generated signature of the conference data.
     *
     * @maps signature
     */
    public function setSignature(?string $signature): void
    {
        $this->signature = $signature;
    }

    /**
     * Converts the ConferenceData object to a human-readable string representation.
     *
     * @return string The string representation of the ConferenceData object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ConferenceData',
            [
                'createRequest' => $this->createRequest,
                'entryPoints' => $this->entryPoints,
                'conferenceSolution' => $this->conferenceSolution,
                'conferenceId' => $this->conferenceId,
                'notes' => $this->notes,
                'signature' => $this->signature,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'createRequest',
        'entryPoints',
        'conferenceSolution',
        'conferenceId',
        'notes',
        'signature'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->createRequest)) {
            $json['createRequest']      = $this->createRequest;
        }
        if (isset($this->entryPoints)) {
            $json['entryPoints']        = $this->entryPoints;
        }
        if (isset($this->conferenceSolution)) {
            $json['conferenceSolution'] = $this->conferenceSolution;
        }
        if (isset($this->conferenceId)) {
            $json['conferenceId']       = $this->conferenceId;
        }
        if (isset($this->notes)) {
            $json['notes']              = $this->notes;
        }
        if (isset($this->signature)) {
            $json['signature']          = $this->signature;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
