<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models;

use CalendarApiLib\ApiHelper;
use stdClass;

/**
 * Conference solution information, such as Google Meet.
 */
class ConferenceSolution implements \JsonSerializable
{
    /**
     * @var ConferenceSolutionKey|null
     */
    private $key;

    /**
     * @var string|null
     */
    private $name;

    /**
     * @var string|null
     */
    private $iconUri;

    /**
     * Returns Key.
     * Identifies a conference solution type.
     */
    public function getKey(): ?ConferenceSolutionKey
    {
        return $this->key;
    }

    /**
     * Sets Key.
     * Identifies a conference solution type.
     *
     * @maps key
     */
    public function setKey(?ConferenceSolutionKey $key): void
    {
        $this->key = $key;
    }

    /**
     * Returns Name.
     * User-visible name of the conference solution.
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * User-visible name of the conference solution.
     *
     * @maps name
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Icon Uri.
     * User-visible icon for this solution.
     */
    public function getIconUri(): ?string
    {
        return $this->iconUri;
    }

    /**
     * Sets Icon Uri.
     * User-visible icon for this solution.
     *
     * @maps iconUri
     */
    public function setIconUri(?string $iconUri): void
    {
        $this->iconUri = $iconUri;
    }

    /**
     * Converts the ConferenceSolution object to a human-readable string representation.
     *
     * @return string The string representation of the ConferenceSolution object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ConferenceSolution',
            [
                'key' => $this->key,
                'name' => $this->name,
                'iconUri' => $this->iconUri,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['key', 'name', 'iconUri'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->key)) {
            $json['key']     = $this->key;
        }
        if (isset($this->name)) {
            $json['name']    = $this->name;
        }
        if (isset($this->iconUri)) {
            $json['iconUri'] = $this->iconUri;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
