<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models;

use CalendarApiLib\ApiHelper;
use stdClass;

/**
 * A request to generate a new conference and attach it to the event.
 */
class ConferenceCreateRequest implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $requestId;

    /**
     * @var ConferenceSolutionKey|null
     */
    private $conferenceSolutionKey;

    /**
     * @var ConferenceCreateRequestStatus|null
     */
    private $status;

    /**
     * Returns Request Id.
     * Unique client-generated ID for this request. Clients should regenerate this ID for every new request.
     */
    public function getRequestId(): ?string
    {
        return $this->requestId;
    }

    /**
     * Sets Request Id.
     * Unique client-generated ID for this request. Clients should regenerate this ID for every new request.
     *
     * @maps requestId
     */
    public function setRequestId(?string $requestId): void
    {
        $this->requestId = $requestId;
    }

    /**
     * Returns Conference Solution Key.
     * Identifies a conference solution type.
     */
    public function getConferenceSolutionKey(): ?ConferenceSolutionKey
    {
        return $this->conferenceSolutionKey;
    }

    /**
     * Sets Conference Solution Key.
     * Identifies a conference solution type.
     *
     * @maps conferenceSolutionKey
     */
    public function setConferenceSolutionKey(?ConferenceSolutionKey $conferenceSolutionKey): void
    {
        $this->conferenceSolutionKey = $conferenceSolutionKey;
    }

    /**
     * Returns Status.
     * Status of the conference create request.
     */
    public function getStatus(): ?ConferenceCreateRequestStatus
    {
        return $this->status;
    }

    /**
     * Sets Status.
     * Status of the conference create request.
     *
     * @maps status
     */
    public function setStatus(?ConferenceCreateRequestStatus $status): void
    {
        $this->status = $status;
    }

    /**
     * Converts the ConferenceCreateRequest object to a human-readable string representation.
     *
     * @return string The string representation of the ConferenceCreateRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ConferenceCreateRequest',
            [
                'requestId' => $this->requestId,
                'conferenceSolutionKey' => $this->conferenceSolutionKey,
                'status' => $this->status,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['requestId', 'conferenceSolutionKey', 'status'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->requestId)) {
            $json['requestId']             = $this->requestId;
        }
        if (isset($this->conferenceSolutionKey)) {
            $json['conferenceSolutionKey'] = $this->conferenceSolutionKey;
        }
        if (isset($this->status)) {
            $json['status']                = $this->status;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
