<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models;

use CalendarApiLib\ApiHelper;
use stdClass;

/**
 * ErrorResponseErrorErrorsItems object.
 */
class ErrorResponseErrorErrorsItems implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $domain;

    /**
     * @var string|null
     */
    private $reason;

    /**
     * @var string|null
     */
    private $message;

    /**
     * Returns Domain.
     * The error domain.
     */
    public function getDomain(): ?string
    {
        return $this->domain;
    }

    /**
     * Sets Domain.
     * The error domain.
     *
     * @maps domain
     */
    public function setDomain(?string $domain): void
    {
        $this->domain = $domain;
    }

    /**
     * Returns Reason.
     * The error reason code.
     */
    public function getReason(): ?string
    {
        return $this->reason;
    }

    /**
     * Sets Reason.
     * The error reason code.
     *
     * @maps reason
     */
    public function setReason(?string $reason): void
    {
        $this->reason = $reason;
    }

    /**
     * Returns Message.
     * A human-readable error message.
     */
    public function getMessage(): ?string
    {
        return $this->message;
    }

    /**
     * Sets Message.
     * A human-readable error message.
     *
     * @maps message
     */
    public function setMessage(?string $message): void
    {
        $this->message = $message;
    }

    /**
     * Converts the ErrorResponseErrorErrorsItems object to a human-readable string representation.
     *
     * @return string The string representation of the ErrorResponseErrorErrorsItems object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ErrorResponseErrorErrorsItems',
            [
                'domain' => $this->domain,
                'reason' => $this->reason,
                'message' => $this->message,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['domain', 'reason', 'message'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->domain)) {
            $json['domain']  = $this->domain;
        }
        if (isset($this->reason)) {
            $json['reason']  = $this->reason;
        }
        if (isset($this->message)) {
            $json['message'] = $this->message;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
