<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models;

use CalendarApiLib\ApiHelper;
use stdClass;

/**
 * Information about the event's reminders.
 */
class EventReminders implements \JsonSerializable
{
    /**
     * @var bool|null
     */
    private $useDefault;

    /**
     * @var Reminder[]|null
     */
    private $overrides;

    /**
     * Returns Use Default.
     * Whether the default reminders of the calendar apply to the event.
     */
    public function getUseDefault(): ?bool
    {
        return $this->useDefault;
    }

    /**
     * Sets Use Default.
     * Whether the default reminders of the calendar apply to the event.
     *
     * @maps useDefault
     */
    public function setUseDefault(?bool $useDefault): void
    {
        $this->useDefault = $useDefault;
    }

    /**
     * Returns Overrides.
     * Overrides to apply instead of default reminders. Maximum 5 overrides.
     *
     * @return Reminder[]|null
     */
    public function getOverrides(): ?array
    {
        return $this->overrides;
    }

    /**
     * Sets Overrides.
     * Overrides to apply instead of default reminders. Maximum 5 overrides.
     *
     * @maps overrides
     *
     * @param Reminder[]|null $overrides
     */
    public function setOverrides(?array $overrides): void
    {
        $this->overrides = $overrides;
    }

    /**
     * Converts the EventReminders object to a human-readable string representation.
     *
     * @return string The string representation of the EventReminders object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'EventReminders',
            [
                'useDefault' => $this->useDefault,
                'overrides' => $this->overrides,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['useDefault', 'overrides'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->useDefault)) {
            $json['useDefault'] = $this->useDefault;
        }
        if (isset($this->overrides)) {
            $json['overrides']  = $this->overrides;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
