<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models;

use CalendarApiLib\ApiHelper;
use CalendarApiLib\Utils\DateTimeHelper;
use stdClass;

/**
 * A timestamp marking the start or end of an event. For all-day events, use date; for timed events,
 * use dateTime.
 */
class EventDateTime implements \JsonSerializable
{
    /**
     * @var \DateTime|null
     */
    private $date;

    /**
     * @var \DateTime|null
     */
    private $dateTime;

    /**
     * @var string|null
     */
    private $timeZone;

    /**
     * Returns Date.
     * The date, in the format "yyyy-mm-dd", if this is an all-day event.
     */
    public function getDate(): ?\DateTime
    {
        return $this->date;
    }

    /**
     * Sets Date.
     * The date, in the format "yyyy-mm-dd", if this is an all-day event.
     *
     * @maps date
     * @factory \CalendarApiLib\Utils\DateTimeHelper::fromSimpleDate
     */
    public function setDate(?\DateTime $date): void
    {
        $this->date = $date;
    }

    /**
     * Returns Date Time.
     * The time, as a combined date-time value (RFC3339). A time zone offset is required unless a time zone
     * is explicitly specified in timeZone.
     */
    public function getDateTime(): ?\DateTime
    {
        return $this->dateTime;
    }

    /**
     * Sets Date Time.
     * The time, as a combined date-time value (RFC3339). A time zone offset is required unless a time zone
     * is explicitly specified in timeZone.
     *
     * @maps dateTime
     * @factory \CalendarApiLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setDateTime(?\DateTime $dateTime): void
    {
        $this->dateTime = $dateTime;
    }

    /**
     * Returns Time Zone.
     * The time zone in which the time is specified. Formatted as an IANA Time Zone Database name, e.g.
     * "America/New_York".
     */
    public function getTimeZone(): ?string
    {
        return $this->timeZone;
    }

    /**
     * Sets Time Zone.
     * The time zone in which the time is specified. Formatted as an IANA Time Zone Database name, e.g.
     * "America/New_York".
     *
     * @maps timeZone
     */
    public function setTimeZone(?string $timeZone): void
    {
        $this->timeZone = $timeZone;
    }

    /**
     * Converts the EventDateTime object to a human-readable string representation.
     *
     * @return string The string representation of the EventDateTime object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'EventDateTime',
            [
                'date' => $this->date,
                'dateTime' => $this->dateTime,
                'timeZone' => $this->timeZone,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['date', 'dateTime', 'timeZone'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->date)) {
            $json['date']     = DateTimeHelper::toSimpleDate($this->date);
        }
        if (isset($this->dateTime)) {
            $json['dateTime'] = DateTimeHelper::toRfc3339DateTime($this->dateTime);
        }
        if (isset($this->timeZone)) {
            $json['timeZone'] = $this->timeZone;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
