<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models;

use CalendarApiLib\ApiHelper;
use CalendarApiLib\Utils\DateTimeHelper;
use stdClass;

/**
 * A Google Calendar event resource.
 */
class Event implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $kind = 'calendar#event';

    /**
     * @var string|null
     */
    private $etag;

    /**
     * @var string|null
     */
    private $id;

    /**
     * @var string|null
     */
    private $status;

    /**
     * @var string|null
     */
    private $htmlLink;

    /**
     * @var \DateTime|null
     */
    private $created;

    /**
     * @var \DateTime|null
     */
    private $updated;

    /**
     * @var string|null
     */
    private $summary;

    /**
     * @var string|null
     */
    private $description;

    /**
     * @var string|null
     */
    private $location;

    /**
     * @var string|null
     */
    private $colorId;

    /**
     * @var Person|null
     */
    private $creator;

    /**
     * @var Person|null
     */
    private $organizer;

    /**
     * @var EventDateTime
     */
    private $start;

    /**
     * @var EventDateTime
     */
    private $end;

    /**
     * @var bool|null
     */
    private $endTimeUnspecified = false;

    /**
     * @var string[]|null
     */
    private $recurrence;

    /**
     * @var string|null
     */
    private $recurringEventId;

    /**
     * @var EventDateTime|null
     */
    private $originalStartTime;

    /**
     * @var string|null
     */
    private $transparency = EventTransparency::OPAQUE;

    /**
     * @var string|null
     */
    private $visibility = EventVisibility::DEFAULT_;

    /**
     * @var string|null
     */
    private $iCalUid;

    /**
     * @var int|null
     */
    private $sequence;

    /**
     * @var Attendee[]|null
     */
    private $attendees;

    /**
     * @var bool|null
     */
    private $attendeesOmitted = false;

    /**
     * @var string|null
     */
    private $hangoutLink;

    /**
     * @var ConferenceData|null
     */
    private $conferenceData;

    /**
     * @var bool|null
     */
    private $guestsCanInviteOthers = true;

    /**
     * @var bool|null
     */
    private $guestsCanModify = false;

    /**
     * @var bool|null
     */
    private $guestsCanSeeOtherGuests = true;

    /**
     * @var bool|null
     */
    private $privateCopy = false;

    /**
     * @var bool|null
     */
    private $locked = false;

    /**
     * @var EventReminders|null
     */
    private $reminders;

    /**
     * @var EventSource|null
     */
    private $source;

    /**
     * @var string|null
     */
    private $eventType;

    /**
     * @var ExtendedProperties|null
     */
    private $extendedProperties;

    /**
     * @var Attachment[]|null
     */
    private $attachments;

    /**
     * @var BirthdayProperties|null
     */
    private $birthdayProperties;

    /**
     * @var OutOfOfficeProperties|null
     */
    private $outOfOfficeProperties;

    /**
     * @var FocusTimeProperties|null
     */
    private $focusTimeProperties;

    /**
     * @var WorkingLocationProperties|null
     */
    private $workingLocationProperties;

    /**
     * @param EventDateTime $start
     * @param EventDateTime $end
     */
    public function __construct(EventDateTime $start, EventDateTime $end)
    {
        $this->start = $start;
        $this->end = $end;
    }

    /**
     * Returns Kind.
     * Type of the resource.
     */
    public function getKind(): ?string
    {
        return $this->kind;
    }

    /**
     * Sets Kind.
     * Type of the resource.
     *
     * @maps kind
     */
    public function setKind(?string $kind): void
    {
        $this->kind = $kind;
    }

    /**
     * Returns Etag.
     * ETag of the resource.
     */
    public function getEtag(): ?string
    {
        return $this->etag;
    }

    /**
     * Sets Etag.
     * ETag of the resource.
     *
     * @maps etag
     */
    public function setEtag(?string $etag): void
    {
        $this->etag = $etag;
    }

    /**
     * Returns Id.
     * Opaque identifier of the event. When creating new single or recurring events, you can specify their
     * IDs. Event IDs must be between 5 and 1024 characters long and consist of lower-case base32hex
     * characters (a-v, 0-9).
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * Opaque identifier of the event. When creating new single or recurring events, you can specify their
     * IDs. Event IDs must be between 5 and 1024 characters long and consist of lower-case base32hex
     * characters (a-v, 0-9).
     *
     * @maps id
     */
    public function setId(?string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Status.
     * Status of the event.
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     * Status of the event.
     *
     * @maps status
     * @factory \CalendarApiLib\Models\EventStatus::checkValue
     */
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Html Link.
     * Absolute link to this event in the Google Calendar Web UI.
     */
    public function getHtmlLink(): ?string
    {
        return $this->htmlLink;
    }

    /**
     * Sets Html Link.
     * Absolute link to this event in the Google Calendar Web UI.
     *
     * @maps htmlLink
     */
    public function setHtmlLink(?string $htmlLink): void
    {
        $this->htmlLink = $htmlLink;
    }

    /**
     * Returns Created.
     * Creation time of the event (RFC3339).
     */
    public function getCreated(): ?\DateTime
    {
        return $this->created;
    }

    /**
     * Sets Created.
     * Creation time of the event (RFC3339).
     *
     * @maps created
     * @factory \CalendarApiLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setCreated(?\DateTime $created): void
    {
        $this->created = $created;
    }

    /**
     * Returns Updated.
     * Last modification time of the event (RFC3339).
     */
    public function getUpdated(): ?\DateTime
    {
        return $this->updated;
    }

    /**
     * Sets Updated.
     * Last modification time of the event (RFC3339).
     *
     * @maps updated
     * @factory \CalendarApiLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setUpdated(?\DateTime $updated): void
    {
        $this->updated = $updated;
    }

    /**
     * Returns Summary.
     * Title of the event.
     */
    public function getSummary(): ?string
    {
        return $this->summary;
    }

    /**
     * Sets Summary.
     * Title of the event.
     *
     * @maps summary
     */
    public function setSummary(?string $summary): void
    {
        $this->summary = $summary;
    }

    /**
     * Returns Description.
     * Description of the event. Can contain HTML.
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     * Description of the event. Can contain HTML.
     *
     * @maps description
     */
    public function setDescription(?string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns Location.
     * Geographic location of the event as free-form text.
     */
    public function getLocation(): ?string
    {
        return $this->location;
    }

    /**
     * Sets Location.
     * Geographic location of the event as free-form text.
     *
     * @maps location
     */
    public function setLocation(?string $location): void
    {
        $this->location = $location;
    }

    /**
     * Returns Color Id.
     * The color of the event. This is an ID referring to an entry in the event section of the colors
     * definition.
     */
    public function getColorId(): ?string
    {
        return $this->colorId;
    }

    /**
     * Sets Color Id.
     * The color of the event. This is an ID referring to an entry in the event section of the colors
     * definition.
     *
     * @maps colorId
     */
    public function setColorId(?string $colorId): void
    {
        $this->colorId = $colorId;
    }

    /**
     * Returns Creator.
     * Identifies a person associated with the event, such as the creator or organizer.
     */
    public function getCreator(): ?Person
    {
        return $this->creator;
    }

    /**
     * Sets Creator.
     * Identifies a person associated with the event, such as the creator or organizer.
     *
     * @maps creator
     */
    public function setCreator(?Person $creator): void
    {
        $this->creator = $creator;
    }

    /**
     * Returns Organizer.
     * Identifies a person associated with the event, such as the creator or organizer.
     */
    public function getOrganizer(): ?Person
    {
        return $this->organizer;
    }

    /**
     * Sets Organizer.
     * Identifies a person associated with the event, such as the creator or organizer.
     *
     * @maps organizer
     */
    public function setOrganizer(?Person $organizer): void
    {
        $this->organizer = $organizer;
    }

    /**
     * Returns Start.
     * A timestamp marking the start or end of an event. For all-day events, use date; for timed events,
     * use dateTime.
     */
    public function getStart(): EventDateTime
    {
        return $this->start;
    }

    /**
     * Sets Start.
     * A timestamp marking the start or end of an event. For all-day events, use date; for timed events,
     * use dateTime.
     *
     * @required
     * @maps start
     */
    public function setStart(EventDateTime $start): void
    {
        $this->start = $start;
    }

    /**
     * Returns End.
     * A timestamp marking the start or end of an event. For all-day events, use date; for timed events,
     * use dateTime.
     */
    public function getEnd(): EventDateTime
    {
        return $this->end;
    }

    /**
     * Sets End.
     * A timestamp marking the start or end of an event. For all-day events, use date; for timed events,
     * use dateTime.
     *
     * @required
     * @maps end
     */
    public function setEnd(EventDateTime $end): void
    {
        $this->end = $end;
    }

    /**
     * Returns End Time Unspecified.
     * Whether the end time is actually unspecified.
     */
    public function getEndTimeUnspecified(): ?bool
    {
        return $this->endTimeUnspecified;
    }

    /**
     * Sets End Time Unspecified.
     * Whether the end time is actually unspecified.
     *
     * @maps endTimeUnspecified
     */
    public function setEndTimeUnspecified(?bool $endTimeUnspecified): void
    {
        $this->endTimeUnspecified = $endTimeUnspecified;
    }

    /**
     * Returns Recurrence.
     * List of RRULE, EXRULE, RDATE, and EXDATE lines for a recurring event, as specified in RFC 5545. This
     * field is omitted for single events or instances of recurring events.
     *
     * @return string[]|null
     */
    public function getRecurrence(): ?array
    {
        return $this->recurrence;
    }

    /**
     * Sets Recurrence.
     * List of RRULE, EXRULE, RDATE, and EXDATE lines for a recurring event, as specified in RFC 5545. This
     * field is omitted for single events or instances of recurring events.
     *
     * @maps recurrence
     *
     * @param string[]|null $recurrence
     */
    public function setRecurrence(?array $recurrence): void
    {
        $this->recurrence = $recurrence;
    }

    /**
     * Returns Recurring Event Id.
     * For an instance of a recurring event, this is the ID of the recurring event to which this instance
     * belongs.
     */
    public function getRecurringEventId(): ?string
    {
        return $this->recurringEventId;
    }

    /**
     * Sets Recurring Event Id.
     * For an instance of a recurring event, this is the ID of the recurring event to which this instance
     * belongs.
     *
     * @maps recurringEventId
     */
    public function setRecurringEventId(?string $recurringEventId): void
    {
        $this->recurringEventId = $recurringEventId;
    }

    /**
     * Returns Original Start Time.
     * A timestamp marking the start or end of an event. For all-day events, use date; for timed events,
     * use dateTime.
     */
    public function getOriginalStartTime(): ?EventDateTime
    {
        return $this->originalStartTime;
    }

    /**
     * Sets Original Start Time.
     * A timestamp marking the start or end of an event. For all-day events, use date; for timed events,
     * use dateTime.
     *
     * @maps originalStartTime
     */
    public function setOriginalStartTime(?EventDateTime $originalStartTime): void
    {
        $this->originalStartTime = $originalStartTime;
    }

    /**
     * Returns Transparency.
     * Whether the event blocks time on the calendar. "opaque" means the event does block time;
     * "transparent" means it does not.
     */
    public function getTransparency(): ?string
    {
        return $this->transparency;
    }

    /**
     * Sets Transparency.
     * Whether the event blocks time on the calendar. "opaque" means the event does block time;
     * "transparent" means it does not.
     *
     * @maps transparency
     * @factory \CalendarApiLib\Models\EventTransparency::checkValue
     */
    public function setTransparency(?string $transparency): void
    {
        $this->transparency = $transparency;
    }

    /**
     * Returns Visibility.
     * Visibility of the event.
     */
    public function getVisibility(): ?string
    {
        return $this->visibility;
    }

    /**
     * Sets Visibility.
     * Visibility of the event.
     *
     * @maps visibility
     * @factory \CalendarApiLib\Models\EventVisibility::checkValue
     */
    public function setVisibility(?string $visibility): void
    {
        $this->visibility = $visibility;
    }

    /**
     * Returns I Cal Uid.
     * Event unique identifier as defined in RFC 5545.
     */
    public function getICalUid(): ?string
    {
        return $this->iCalUid;
    }

    /**
     * Sets I Cal Uid.
     * Event unique identifier as defined in RFC 5545.
     *
     * @maps iCalUID
     */
    public function setICalUid(?string $iCalUid): void
    {
        $this->iCalUid = $iCalUid;
    }

    /**
     * Returns Sequence.
     * Sequence number as per iCalendar.
     */
    public function getSequence(): ?int
    {
        return $this->sequence;
    }

    /**
     * Sets Sequence.
     * Sequence number as per iCalendar.
     *
     * @maps sequence
     */
    public function setSequence(?int $sequence): void
    {
        $this->sequence = $sequence;
    }

    /**
     * Returns Attendees.
     * The attendees of the event.
     *
     * @return Attendee[]|null
     */
    public function getAttendees(): ?array
    {
        return $this->attendees;
    }

    /**
     * Sets Attendees.
     * The attendees of the event.
     *
     * @maps attendees
     *
     * @param Attendee[]|null $attendees
     */
    public function setAttendees(?array $attendees): void
    {
        $this->attendees = $attendees;
    }

    /**
     * Returns Attendees Omitted.
     * Whether attendees may have been omitted from the event's representation.
     */
    public function getAttendeesOmitted(): ?bool
    {
        return $this->attendeesOmitted;
    }

    /**
     * Sets Attendees Omitted.
     * Whether attendees may have been omitted from the event's representation.
     *
     * @maps attendeesOmitted
     */
    public function setAttendeesOmitted(?bool $attendeesOmitted): void
    {
        $this->attendeesOmitted = $attendeesOmitted;
    }

    /**
     * Returns Hangout Link.
     * An absolute link to the Google Hangout associated with this event (deprecated in favor of
     * conferenceData).
     */
    public function getHangoutLink(): ?string
    {
        return $this->hangoutLink;
    }

    /**
     * Sets Hangout Link.
     * An absolute link to the Google Hangout associated with this event (deprecated in favor of
     * conferenceData).
     *
     * @maps hangoutLink
     */
    public function setHangoutLink(?string $hangoutLink): void
    {
        $this->hangoutLink = $hangoutLink;
    }

    /**
     * Returns Conference Data.
     * Information about a conference (e.g. Google Meet).
     */
    public function getConferenceData(): ?ConferenceData
    {
        return $this->conferenceData;
    }

    /**
     * Sets Conference Data.
     * Information about a conference (e.g. Google Meet).
     *
     * @maps conferenceData
     */
    public function setConferenceData(?ConferenceData $conferenceData): void
    {
        $this->conferenceData = $conferenceData;
    }

    /**
     * Returns Guests Can Invite Others.
     * Whether attendees other than the organizer can invite others.
     */
    public function getGuestsCanInviteOthers(): ?bool
    {
        return $this->guestsCanInviteOthers;
    }

    /**
     * Sets Guests Can Invite Others.
     * Whether attendees other than the organizer can invite others.
     *
     * @maps guestsCanInviteOthers
     */
    public function setGuestsCanInviteOthers(?bool $guestsCanInviteOthers): void
    {
        $this->guestsCanInviteOthers = $guestsCanInviteOthers;
    }

    /**
     * Returns Guests Can Modify.
     * Whether attendees other than the organizer can modify the event.
     */
    public function getGuestsCanModify(): ?bool
    {
        return $this->guestsCanModify;
    }

    /**
     * Sets Guests Can Modify.
     * Whether attendees other than the organizer can modify the event.
     *
     * @maps guestsCanModify
     */
    public function setGuestsCanModify(?bool $guestsCanModify): void
    {
        $this->guestsCanModify = $guestsCanModify;
    }

    /**
     * Returns Guests Can See Other Guests.
     * Whether attendees other than the organizer can see who the event's attendees are.
     */
    public function getGuestsCanSeeOtherGuests(): ?bool
    {
        return $this->guestsCanSeeOtherGuests;
    }

    /**
     * Sets Guests Can See Other Guests.
     * Whether attendees other than the organizer can see who the event's attendees are.
     *
     * @maps guestsCanSeeOtherGuests
     */
    public function setGuestsCanSeeOtherGuests(?bool $guestsCanSeeOtherGuests): void
    {
        $this->guestsCanSeeOtherGuests = $guestsCanSeeOtherGuests;
    }

    /**
     * Returns Private Copy.
     * If set to true, event propagation is disabled.
     */
    public function getPrivateCopy(): ?bool
    {
        return $this->privateCopy;
    }

    /**
     * Sets Private Copy.
     * If set to true, event propagation is disabled.
     *
     * @maps privateCopy
     */
    public function setPrivateCopy(?bool $privateCopy): void
    {
        $this->privateCopy = $privateCopy;
    }

    /**
     * Returns Locked.
     * Whether this is a locked event copy where no changes can be made.
     */
    public function getLocked(): ?bool
    {
        return $this->locked;
    }

    /**
     * Sets Locked.
     * Whether this is a locked event copy where no changes can be made.
     *
     * @maps locked
     */
    public function setLocked(?bool $locked): void
    {
        $this->locked = $locked;
    }

    /**
     * Returns Reminders.
     * Information about the event's reminders.
     */
    public function getReminders(): ?EventReminders
    {
        return $this->reminders;
    }

    /**
     * Sets Reminders.
     * Information about the event's reminders.
     *
     * @maps reminders
     */
    public function setReminders(?EventReminders $reminders): void
    {
        $this->reminders = $reminders;
    }

    /**
     * Returns Source.
     * Source from which the event was created — for example, a web page or an email message.
     */
    public function getSource(): ?EventSource
    {
        return $this->source;
    }

    /**
     * Sets Source.
     * Source from which the event was created — for example, a web page or an email message.
     *
     * @maps source
     */
    public function setSource(?EventSource $source): void
    {
        $this->source = $source;
    }

    /**
     * Returns Event Type.
     * The specific type of event.
     */
    public function getEventType(): ?string
    {
        return $this->eventType;
    }

    /**
     * Sets Event Type.
     * The specific type of event.
     *
     * @maps eventType
     * @factory \CalendarApiLib\Models\EventType::checkValue
     */
    public function setEventType(?string $eventType): void
    {
        $this->eventType = $eventType;
    }

    /**
     * Returns Extended Properties.
     * Extended properties of the event.
     */
    public function getExtendedProperties(): ?ExtendedProperties
    {
        return $this->extendedProperties;
    }

    /**
     * Sets Extended Properties.
     * Extended properties of the event.
     *
     * @maps extendedProperties
     */
    public function setExtendedProperties(?ExtendedProperties $extendedProperties): void
    {
        $this->extendedProperties = $extendedProperties;
    }

    /**
     * Returns Attachments.
     * File attachments for the event. Maximum 25 attachments per event.
     *
     * @return Attachment[]|null
     */
    public function getAttachments(): ?array
    {
        return $this->attachments;
    }

    /**
     * Sets Attachments.
     * File attachments for the event. Maximum 25 attachments per event.
     *
     * @maps attachments
     *
     * @param Attachment[]|null $attachments
     */
    public function setAttachments(?array $attachments): void
    {
        $this->attachments = $attachments;
    }

    /**
     * Returns Birthday Properties.
     * Birthday or special event data. Used if eventType is birthday.
     */
    public function getBirthdayProperties(): ?BirthdayProperties
    {
        return $this->birthdayProperties;
    }

    /**
     * Sets Birthday Properties.
     * Birthday or special event data. Used if eventType is birthday.
     *
     * @maps birthdayProperties
     */
    public function setBirthdayProperties(?BirthdayProperties $birthdayProperties): void
    {
        $this->birthdayProperties = $birthdayProperties;
    }

    /**
     * Returns Out of Office Properties.
     * Out-of-office event data. Used if eventType is outOfOffice.
     */
    public function getOutOfOfficeProperties(): ?OutOfOfficeProperties
    {
        return $this->outOfOfficeProperties;
    }

    /**
     * Sets Out of Office Properties.
     * Out-of-office event data. Used if eventType is outOfOffice.
     *
     * @maps outOfOfficeProperties
     */
    public function setOutOfOfficeProperties(?OutOfOfficeProperties $outOfOfficeProperties): void
    {
        $this->outOfOfficeProperties = $outOfOfficeProperties;
    }

    /**
     * Returns Focus Time Properties.
     * Focus time event data. Used if eventType is focusTime.
     */
    public function getFocusTimeProperties(): ?FocusTimeProperties
    {
        return $this->focusTimeProperties;
    }

    /**
     * Sets Focus Time Properties.
     * Focus time event data. Used if eventType is focusTime.
     *
     * @maps focusTimeProperties
     */
    public function setFocusTimeProperties(?FocusTimeProperties $focusTimeProperties): void
    {
        $this->focusTimeProperties = $focusTimeProperties;
    }

    /**
     * Returns Working Location Properties.
     * Working location event data. Used if eventType is workingLocation.
     */
    public function getWorkingLocationProperties(): ?WorkingLocationProperties
    {
        return $this->workingLocationProperties;
    }

    /**
     * Sets Working Location Properties.
     * Working location event data. Used if eventType is workingLocation.
     *
     * @maps workingLocationProperties
     */
    public function setWorkingLocationProperties(?WorkingLocationProperties $workingLocationProperties): void
    {
        $this->workingLocationProperties = $workingLocationProperties;
    }

    /**
     * Converts the Event object to a human-readable string representation.
     *
     * @return string The string representation of the Event object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Event',
            [
                'kind' => $this->kind,
                'etag' => $this->etag,
                'id' => $this->id,
                'status' => $this->status,
                'htmlLink' => $this->htmlLink,
                'created' => $this->created,
                'updated' => $this->updated,
                'summary' => $this->summary,
                'description' => $this->description,
                'location' => $this->location,
                'colorId' => $this->colorId,
                'creator' => $this->creator,
                'organizer' => $this->organizer,
                'start' => $this->start,
                'end' => $this->end,
                'endTimeUnspecified' => $this->endTimeUnspecified,
                'recurrence' => $this->recurrence,
                'recurringEventId' => $this->recurringEventId,
                'originalStartTime' => $this->originalStartTime,
                'transparency' => $this->transparency,
                'visibility' => $this->visibility,
                'iCalUid' => $this->iCalUid,
                'sequence' => $this->sequence,
                'attendees' => $this->attendees,
                'attendeesOmitted' => $this->attendeesOmitted,
                'hangoutLink' => $this->hangoutLink,
                'conferenceData' => $this->conferenceData,
                'guestsCanInviteOthers' => $this->guestsCanInviteOthers,
                'guestsCanModify' => $this->guestsCanModify,
                'guestsCanSeeOtherGuests' => $this->guestsCanSeeOtherGuests,
                'privateCopy' => $this->privateCopy,
                'locked' => $this->locked,
                'reminders' => $this->reminders,
                'source' => $this->source,
                'eventType' => $this->eventType,
                'extendedProperties' => $this->extendedProperties,
                'attachments' => $this->attachments,
                'birthdayProperties' => $this->birthdayProperties,
                'outOfOfficeProperties' => $this->outOfOfficeProperties,
                'focusTimeProperties' => $this->focusTimeProperties,
                'workingLocationProperties' => $this->workingLocationProperties,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'kind',
        'etag',
        'id',
        'status',
        'htmlLink',
        'created',
        'updated',
        'summary',
        'description',
        'location',
        'colorId',
        'creator',
        'organizer',
        'start',
        'end',
        'endTimeUnspecified',
        'recurrence',
        'recurringEventId',
        'originalStartTime',
        'transparency',
        'visibility',
        'iCalUID',
        'sequence',
        'attendees',
        'attendeesOmitted',
        'hangoutLink',
        'conferenceData',
        'guestsCanInviteOthers',
        'guestsCanModify',
        'guestsCanSeeOtherGuests',
        'privateCopy',
        'locked',
        'reminders',
        'source',
        'eventType',
        'extendedProperties',
        'attachments',
        'birthdayProperties',
        'outOfOfficeProperties',
        'focusTimeProperties',
        'workingLocationProperties'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->kind)) {
            $json['kind']                      = $this->kind;
        }
        if (isset($this->etag)) {
            $json['etag']                      = $this->etag;
        }
        if (isset($this->id)) {
            $json['id']                        = $this->id;
        }
        if (isset($this->status)) {
            $json['status']                    = EventStatus::checkValue($this->status);
        }
        if (isset($this->htmlLink)) {
            $json['htmlLink']                  = $this->htmlLink;
        }
        if (isset($this->created)) {
            $json['created']                   = DateTimeHelper::toRfc3339DateTime($this->created);
        }
        if (isset($this->updated)) {
            $json['updated']                   = DateTimeHelper::toRfc3339DateTime($this->updated);
        }
        if (isset($this->summary)) {
            $json['summary']                   = $this->summary;
        }
        if (isset($this->description)) {
            $json['description']               = $this->description;
        }
        if (isset($this->location)) {
            $json['location']                  = $this->location;
        }
        if (isset($this->colorId)) {
            $json['colorId']                   = $this->colorId;
        }
        if (isset($this->creator)) {
            $json['creator']                   = $this->creator;
        }
        if (isset($this->organizer)) {
            $json['organizer']                 = $this->organizer;
        }
        $json['start']                         = $this->start;
        $json['end']                           = $this->end;
        if (isset($this->endTimeUnspecified)) {
            $json['endTimeUnspecified']        = $this->endTimeUnspecified;
        }
        if (isset($this->recurrence)) {
            $json['recurrence']                = $this->recurrence;
        }
        if (isset($this->recurringEventId)) {
            $json['recurringEventId']          = $this->recurringEventId;
        }
        if (isset($this->originalStartTime)) {
            $json['originalStartTime']         = $this->originalStartTime;
        }
        if (isset($this->transparency)) {
            $json['transparency']              = EventTransparency::checkValue($this->transparency);
        }
        if (isset($this->visibility)) {
            $json['visibility']                = EventVisibility::checkValue($this->visibility);
        }
        if (isset($this->iCalUid)) {
            $json['iCalUID']                   = $this->iCalUid;
        }
        if (isset($this->sequence)) {
            $json['sequence']                  = $this->sequence;
        }
        if (isset($this->attendees)) {
            $json['attendees']                 = $this->attendees;
        }
        if (isset($this->attendeesOmitted)) {
            $json['attendeesOmitted']          = $this->attendeesOmitted;
        }
        if (isset($this->hangoutLink)) {
            $json['hangoutLink']               = $this->hangoutLink;
        }
        if (isset($this->conferenceData)) {
            $json['conferenceData']            = $this->conferenceData;
        }
        if (isset($this->guestsCanInviteOthers)) {
            $json['guestsCanInviteOthers']     = $this->guestsCanInviteOthers;
        }
        if (isset($this->guestsCanModify)) {
            $json['guestsCanModify']           = $this->guestsCanModify;
        }
        if (isset($this->guestsCanSeeOtherGuests)) {
            $json['guestsCanSeeOtherGuests']   = $this->guestsCanSeeOtherGuests;
        }
        if (isset($this->privateCopy)) {
            $json['privateCopy']               = $this->privateCopy;
        }
        if (isset($this->locked)) {
            $json['locked']                    = $this->locked;
        }
        if (isset($this->reminders)) {
            $json['reminders']                 = $this->reminders;
        }
        if (isset($this->source)) {
            $json['source']                    = $this->source;
        }
        if (isset($this->eventType)) {
            $json['eventType']                 = EventType::checkValue($this->eventType);
        }
        if (isset($this->extendedProperties)) {
            $json['extendedProperties']        = $this->extendedProperties;
        }
        if (isset($this->attachments)) {
            $json['attachments']               = $this->attachments;
        }
        if (isset($this->birthdayProperties)) {
            $json['birthdayProperties']        = $this->birthdayProperties;
        }
        if (isset($this->outOfOfficeProperties)) {
            $json['outOfOfficeProperties']     = $this->outOfOfficeProperties;
        }
        if (isset($this->focusTimeProperties)) {
            $json['focusTimeProperties']       = $this->focusTimeProperties;
        }
        if (isset($this->workingLocationProperties)) {
            $json['workingLocationProperties'] = $this->workingLocationProperties;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
