<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models;

use CalendarApiLib\ApiHelper;
use CalendarApiLib\Utils\DateTimeHelper;
use stdClass;

/**
 * A paginated list of events on a calendar.
 */
class EventList implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $kind = 'calendar#events';

    /**
     * @var string|null
     */
    private $etag;

    /**
     * @var string|null
     */
    private $summary;

    /**
     * @var string|null
     */
    private $description;

    /**
     * @var \DateTime|null
     */
    private $updated;

    /**
     * @var string|null
     */
    private $timeZone;

    /**
     * @var string|null
     */
    private $accessRole;

    /**
     * @var Reminder[]|null
     */
    private $defaultReminders;

    /**
     * @var string|null
     */
    private $nextPageToken;

    /**
     * @var string|null
     */
    private $nextSyncToken;

    /**
     * @var Event[]|null
     */
    private $items;

    /**
     * Returns Kind.
     * Type of the collection.
     */
    public function getKind(): ?string
    {
        return $this->kind;
    }

    /**
     * Sets Kind.
     * Type of the collection.
     *
     * @maps kind
     */
    public function setKind(?string $kind): void
    {
        $this->kind = $kind;
    }

    /**
     * Returns Etag.
     * ETag of the collection.
     */
    public function getEtag(): ?string
    {
        return $this->etag;
    }

    /**
     * Sets Etag.
     * ETag of the collection.
     *
     * @maps etag
     */
    public function setEtag(?string $etag): void
    {
        $this->etag = $etag;
    }

    /**
     * Returns Summary.
     * Title of the calendar.
     */
    public function getSummary(): ?string
    {
        return $this->summary;
    }

    /**
     * Sets Summary.
     * Title of the calendar.
     *
     * @maps summary
     */
    public function setSummary(?string $summary): void
    {
        $this->summary = $summary;
    }

    /**
     * Returns Description.
     * Description of the calendar.
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     * Description of the calendar.
     *
     * @maps description
     */
    public function setDescription(?string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns Updated.
     * Last modification time of the calendar (RFC3339).
     */
    public function getUpdated(): ?\DateTime
    {
        return $this->updated;
    }

    /**
     * Sets Updated.
     * Last modification time of the calendar (RFC3339).
     *
     * @maps updated
     * @factory \CalendarApiLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setUpdated(?\DateTime $updated): void
    {
        $this->updated = $updated;
    }

    /**
     * Returns Time Zone.
     * The time zone of the calendar.
     */
    public function getTimeZone(): ?string
    {
        return $this->timeZone;
    }

    /**
     * Sets Time Zone.
     * The time zone of the calendar.
     *
     * @maps timeZone
     */
    public function setTimeZone(?string $timeZone): void
    {
        $this->timeZone = $timeZone;
    }

    /**
     * Returns Access Role.
     * The user's access role for a calendar.
     */
    public function getAccessRole(): ?string
    {
        return $this->accessRole;
    }

    /**
     * Sets Access Role.
     * The user's access role for a calendar.
     *
     * @maps accessRole
     * @factory \CalendarApiLib\Models\CalendarAccessRole::checkValue
     */
    public function setAccessRole(?string $accessRole): void
    {
        $this->accessRole = $accessRole;
    }

    /**
     * Returns Default Reminders.
     * Default reminders on the calendar for the authenticated user.
     *
     * @return Reminder[]|null
     */
    public function getDefaultReminders(): ?array
    {
        return $this->defaultReminders;
    }

    /**
     * Sets Default Reminders.
     * Default reminders on the calendar for the authenticated user.
     *
     * @maps defaultReminders
     *
     * @param Reminder[]|null $defaultReminders
     */
    public function setDefaultReminders(?array $defaultReminders): void
    {
        $this->defaultReminders = $defaultReminders;
    }

    /**
     * Returns Next Page Token.
     * Token used to access the next page of this result. Omitted if no further results are available.
     */
    public function getNextPageToken(): ?string
    {
        return $this->nextPageToken;
    }

    /**
     * Sets Next Page Token.
     * Token used to access the next page of this result. Omitted if no further results are available.
     *
     * @maps nextPageToken
     */
    public function setNextPageToken(?string $nextPageToken): void
    {
        $this->nextPageToken = $nextPageToken;
    }

    /**
     * Returns Next Sync Token.
     * Token used for incremental synchronization at a later point. Only provided on the last page of
     * results.
     */
    public function getNextSyncToken(): ?string
    {
        return $this->nextSyncToken;
    }

    /**
     * Sets Next Sync Token.
     * Token used for incremental synchronization at a later point. Only provided on the last page of
     * results.
     *
     * @maps nextSyncToken
     */
    public function setNextSyncToken(?string $nextSyncToken): void
    {
        $this->nextSyncToken = $nextSyncToken;
    }

    /**
     * Returns Items.
     * List of events on the calendar.
     *
     * @return Event[]|null
     */
    public function getItems(): ?array
    {
        return $this->items;
    }

    /**
     * Sets Items.
     * List of events on the calendar.
     *
     * @maps items
     *
     * @param Event[]|null $items
     */
    public function setItems(?array $items): void
    {
        $this->items = $items;
    }

    /**
     * Converts the EventList object to a human-readable string representation.
     *
     * @return string The string representation of the EventList object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'EventList',
            [
                'kind' => $this->kind,
                'etag' => $this->etag,
                'summary' => $this->summary,
                'description' => $this->description,
                'updated' => $this->updated,
                'timeZone' => $this->timeZone,
                'accessRole' => $this->accessRole,
                'defaultReminders' => $this->defaultReminders,
                'nextPageToken' => $this->nextPageToken,
                'nextSyncToken' => $this->nextSyncToken,
                'items' => $this->items,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'kind',
        'etag',
        'summary',
        'description',
        'updated',
        'timeZone',
        'accessRole',
        'defaultReminders',
        'nextPageToken',
        'nextSyncToken',
        'items'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->kind)) {
            $json['kind']             = $this->kind;
        }
        if (isset($this->etag)) {
            $json['etag']             = $this->etag;
        }
        if (isset($this->summary)) {
            $json['summary']          = $this->summary;
        }
        if (isset($this->description)) {
            $json['description']      = $this->description;
        }
        if (isset($this->updated)) {
            $json['updated']          = DateTimeHelper::toRfc3339DateTime($this->updated);
        }
        if (isset($this->timeZone)) {
            $json['timeZone']         = $this->timeZone;
        }
        if (isset($this->accessRole)) {
            $json['accessRole']       = CalendarAccessRole::checkValue($this->accessRole);
        }
        if (isset($this->defaultReminders)) {
            $json['defaultReminders'] = $this->defaultReminders;
        }
        if (isset($this->nextPageToken)) {
            $json['nextPageToken']    = $this->nextPageToken;
        }
        if (isset($this->nextSyncToken)) {
            $json['nextSyncToken']    = $this->nextSyncToken;
        }
        if (isset($this->items)) {
            $json['items']            = $this->items;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
