<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models;

use CalendarApiLib\ApiHelper;
use stdClass;

/**
 * Focus time event data. Used if eventType is focusTime.
 */
class FocusTimeProperties implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $autoDeclineMode;

    /**
     * @var string|null
     */
    private $declineMessage;

    /**
     * @var string|null
     */
    private $chatStatus;

    /**
     * Returns Auto Decline Mode.
     * Whether to auto-decline conflicting meeting invitations.
     */
    public function getAutoDeclineMode(): ?string
    {
        return $this->autoDeclineMode;
    }

    /**
     * Sets Auto Decline Mode.
     * Whether to auto-decline conflicting meeting invitations.
     *
     * @maps autoDeclineMode
     * @factory \CalendarApiLib\Models\AutoDeclineMode::checkValue
     */
    public function setAutoDeclineMode(?string $autoDeclineMode): void
    {
        $this->autoDeclineMode = $autoDeclineMode;
    }

    /**
     * Returns Decline Message.
     * Response message to set when auto-declining invitations.
     */
    public function getDeclineMessage(): ?string
    {
        return $this->declineMessage;
    }

    /**
     * Sets Decline Message.
     * Response message to set when auto-declining invitations.
     *
     * @maps declineMessage
     */
    public function setDeclineMessage(?string $declineMessage): void
    {
        $this->declineMessage = $declineMessage;
    }

    /**
     * Returns Chat Status.
     * Chat status during focus time.
     */
    public function getChatStatus(): ?string
    {
        return $this->chatStatus;
    }

    /**
     * Sets Chat Status.
     * Chat status during focus time.
     *
     * @maps chatStatus
     * @factory \CalendarApiLib\Models\ChatStatus::checkValue
     */
    public function setChatStatus(?string $chatStatus): void
    {
        $this->chatStatus = $chatStatus;
    }

    /**
     * Converts the FocusTimeProperties object to a human-readable string representation.
     *
     * @return string The string representation of the FocusTimeProperties object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'FocusTimeProperties',
            [
                'autoDeclineMode' => $this->autoDeclineMode,
                'declineMessage' => $this->declineMessage,
                'chatStatus' => $this->chatStatus,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['autoDeclineMode', 'declineMessage', 'chatStatus'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->autoDeclineMode)) {
            $json['autoDeclineMode'] = AutoDeclineMode::checkValue($this->autoDeclineMode);
        }
        if (isset($this->declineMessage)) {
            $json['declineMessage']  = $this->declineMessage;
        }
        if (isset($this->chatStatus)) {
            $json['chatStatus']      = ChatStatus::checkValue($this->chatStatus);
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
