<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models;

use CalendarApiLib\ApiHelper;
use stdClass;

/**
 * Expansion result for a single group.
 */
class FreeBusyGroup implements \JsonSerializable
{
    /**
     * @var string[]|null
     */
    private $calendars;

    /**
     * @var FreeBusyError[]|null
     */
    private $errors;

    /**
     * Returns Calendars.
     * List of calendars that are members of this group.
     *
     * @return string[]|null
     */
    public function getCalendars(): ?array
    {
        return $this->calendars;
    }

    /**
     * Sets Calendars.
     * List of calendars that are members of this group.
     *
     * @maps calendars
     *
     * @param string[]|null $calendars
     */
    public function setCalendars(?array $calendars): void
    {
        $this->calendars = $calendars;
    }

    /**
     * Returns Errors.
     * Optional errors for this group.
     *
     * @return FreeBusyError[]|null
     */
    public function getErrors(): ?array
    {
        return $this->errors;
    }

    /**
     * Sets Errors.
     * Optional errors for this group.
     *
     * @maps errors
     *
     * @param FreeBusyError[]|null $errors
     */
    public function setErrors(?array $errors): void
    {
        $this->errors = $errors;
    }

    /**
     * Converts the FreeBusyGroup object to a human-readable string representation.
     *
     * @return string The string representation of the FreeBusyGroup object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'FreeBusyGroup',
            [
                'calendars' => $this->calendars,
                'errors' => $this->errors,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['calendars', 'errors'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->calendars)) {
            $json['calendars'] = $this->calendars;
        }
        if (isset($this->errors)) {
            $json['errors']    = $this->errors;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
