<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models;

use CalendarApiLib\ApiHelper;
use CalendarApiLib\Utils\DateTimeHelper;
use stdClass;

/**
 * Request body for querying free/busy information.
 */
class FreeBusyRequest implements \JsonSerializable
{
    /**
     * @var \DateTime
     */
    private $timeMin;

    /**
     * @var \DateTime
     */
    private $timeMax;

    /**
     * @var string|null
     */
    private $timeZone;

    /**
     * @var int|null
     */
    private $groupExpansionMax;

    /**
     * @var int|null
     */
    private $calendarExpansionMax;

    /**
     * @var FreeBusyRequestItem[]
     */
    private $items;

    /**
     * @param \DateTime $timeMin
     * @param \DateTime $timeMax
     * @param FreeBusyRequestItem[] $items
     */
    public function __construct(\DateTime $timeMin, \DateTime $timeMax, array $items)
    {
        $this->timeMin = $timeMin;
        $this->timeMax = $timeMax;
        $this->items = $items;
    }

    /**
     * Returns Time Min.
     * The start of the interval for the query (RFC3339).
     */
    public function getTimeMin(): \DateTime
    {
        return $this->timeMin;
    }

    /**
     * Sets Time Min.
     * The start of the interval for the query (RFC3339).
     *
     * @required
     * @maps timeMin
     * @factory \CalendarApiLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setTimeMin(\DateTime $timeMin): void
    {
        $this->timeMin = $timeMin;
    }

    /**
     * Returns Time Max.
     * The end of the interval for the query (RFC3339).
     */
    public function getTimeMax(): \DateTime
    {
        return $this->timeMax;
    }

    /**
     * Sets Time Max.
     * The end of the interval for the query (RFC3339).
     *
     * @required
     * @maps timeMax
     * @factory \CalendarApiLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setTimeMax(\DateTime $timeMax): void
    {
        $this->timeMax = $timeMax;
    }

    /**
     * Returns Time Zone.
     * Time zone used in the response. Optional. Defaults to UTC.
     */
    public function getTimeZone(): ?string
    {
        return $this->timeZone;
    }

    /**
     * Sets Time Zone.
     * Time zone used in the response. Optional. Defaults to UTC.
     *
     * @maps timeZone
     */
    public function setTimeZone(?string $timeZone): void
    {
        $this->timeZone = $timeZone;
    }

    /**
     * Returns Group Expansion Max.
     * Maximal number of calendar identifiers to be provided for a single group. Maximum value is 100.
     */
    public function getGroupExpansionMax(): ?int
    {
        return $this->groupExpansionMax;
    }

    /**
     * Sets Group Expansion Max.
     * Maximal number of calendar identifiers to be provided for a single group. Maximum value is 100.
     *
     * @maps groupExpansionMax
     */
    public function setGroupExpansionMax(?int $groupExpansionMax): void
    {
        $this->groupExpansionMax = $groupExpansionMax;
    }

    /**
     * Returns Calendar Expansion Max.
     * Maximal number of calendars whose free/busy information is to be returned. Maximum value is 50.
     */
    public function getCalendarExpansionMax(): ?int
    {
        return $this->calendarExpansionMax;
    }

    /**
     * Sets Calendar Expansion Max.
     * Maximal number of calendars whose free/busy information is to be returned. Maximum value is 50.
     *
     * @maps calendarExpansionMax
     */
    public function setCalendarExpansionMax(?int $calendarExpansionMax): void
    {
        $this->calendarExpansionMax = $calendarExpansionMax;
    }

    /**
     * Returns Items.
     * List of calendars and/or groups to query.
     *
     * @return FreeBusyRequestItem[]
     */
    public function getItems(): array
    {
        return $this->items;
    }

    /**
     * Sets Items.
     * List of calendars and/or groups to query.
     *
     * @required
     * @maps items
     *
     * @param FreeBusyRequestItem[] $items
     */
    public function setItems(array $items): void
    {
        $this->items = $items;
    }

    /**
     * Converts the FreeBusyRequest object to a human-readable string representation.
     *
     * @return string The string representation of the FreeBusyRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'FreeBusyRequest',
            [
                'timeMin' => $this->timeMin,
                'timeMax' => $this->timeMax,
                'timeZone' => $this->timeZone,
                'groupExpansionMax' => $this->groupExpansionMax,
                'calendarExpansionMax' => $this->calendarExpansionMax,
                'items' => $this->items,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['timeMin', 'timeMax', 'timeZone', 'groupExpansionMax', 'calendarExpansionMax', 'items'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['timeMin']                  = DateTimeHelper::toRfc3339DateTime($this->timeMin);
        $json['timeMax']                  = DateTimeHelper::toRfc3339DateTime($this->timeMax);
        if (isset($this->timeZone)) {
            $json['timeZone']             = $this->timeZone;
        }
        if (isset($this->groupExpansionMax)) {
            $json['groupExpansionMax']    = $this->groupExpansionMax;
        }
        if (isset($this->calendarExpansionMax)) {
            $json['calendarExpansionMax'] = $this->calendarExpansionMax;
        }
        $json['items']                    = $this->items;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
