<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models;

use CalendarApiLib\ApiHelper;
use CalendarApiLib\Utils\DateTimeHelper;
use stdClass;

/**
 * Response with free/busy information.
 */
class FreeBusyResponse implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $kind = 'calendar#freeBusy';

    /**
     * @var \DateTime|null
     */
    private $timeMin;

    /**
     * @var \DateTime|null
     */
    private $timeMax;

    /**
     * @var array<string,FreeBusyCalendar>|null
     */
    private $calendars;

    /**
     * @var array<string,FreeBusyGroup>|null
     */
    private $groups;

    /**
     * Returns Kind.
     * Type of the resource.
     */
    public function getKind(): ?string
    {
        return $this->kind;
    }

    /**
     * Sets Kind.
     * Type of the resource.
     *
     * @maps kind
     */
    public function setKind(?string $kind): void
    {
        $this->kind = $kind;
    }

    /**
     * Returns Time Min.
     * The start of the time range queried.
     */
    public function getTimeMin(): ?\DateTime
    {
        return $this->timeMin;
    }

    /**
     * Sets Time Min.
     * The start of the time range queried.
     *
     * @maps timeMin
     * @factory \CalendarApiLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setTimeMin(?\DateTime $timeMin): void
    {
        $this->timeMin = $timeMin;
    }

    /**
     * Returns Time Max.
     * The end of the time range queried.
     */
    public function getTimeMax(): ?\DateTime
    {
        return $this->timeMax;
    }

    /**
     * Sets Time Max.
     * The end of the time range queried.
     *
     * @maps timeMax
     * @factory \CalendarApiLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setTimeMax(?\DateTime $timeMax): void
    {
        $this->timeMax = $timeMax;
    }

    /**
     * Returns Calendars.
     * Free/busy information for each requested calendar.
     *
     * @return array<string,FreeBusyCalendar>|null
     */
    public function getCalendars(): ?array
    {
        return $this->calendars;
    }

    /**
     * Sets Calendars.
     * Free/busy information for each requested calendar.
     *
     * @maps calendars
     *
     * @param array<string,FreeBusyCalendar>|null $calendars
     */
    public function setCalendars(?array $calendars): void
    {
        $this->calendars = $calendars;
    }

    /**
     * Returns Groups.
     * Expansion of groups.
     *
     * @return array<string,FreeBusyGroup>|null
     */
    public function getGroups(): ?array
    {
        return $this->groups;
    }

    /**
     * Sets Groups.
     * Expansion of groups.
     *
     * @maps groups
     *
     * @param array<string,FreeBusyGroup>|null $groups
     */
    public function setGroups(?array $groups): void
    {
        $this->groups = $groups;
    }

    /**
     * Converts the FreeBusyResponse object to a human-readable string representation.
     *
     * @return string The string representation of the FreeBusyResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'FreeBusyResponse',
            [
                'kind' => $this->kind,
                'timeMin' => $this->timeMin,
                'timeMax' => $this->timeMax,
                'calendars' => $this->calendars,
                'groups' => $this->groups,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['kind', 'timeMin', 'timeMax', 'calendars', 'groups'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->kind)) {
            $json['kind']      = $this->kind;
        }
        if (isset($this->timeMin)) {
            $json['timeMin']   = DateTimeHelper::toRfc3339DateTime($this->timeMin);
        }
        if (isset($this->timeMax)) {
            $json['timeMax']   = DateTimeHelper::toRfc3339DateTime($this->timeMax);
        }
        if (isset($this->calendars)) {
            $json['calendars'] = $this->calendars;
        }
        if (isset($this->groups)) {
            $json['groups']    = $this->groups;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
