<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * OAuth 2 scopes supported by the API
 */
class OauthScope
{
    /**
     * See and download any calendar you can access using your Google Calendar.
     */
    public const HTTPS_WWW_GOOGLEAPIS_COM_AUTH_CALENDAR_READONLY = 'https://www.googleapis.com/auth/calendar.readonly';

    /**
     * View and edit events on all your calendars.
     */
    public const HTTPS_WWW_GOOGLEAPIS_COM_AUTH_CALENDAR_EVENTS = 'https://www.googleapis.com/auth/calendar.events';

    /**
     * See, edit, share, and permanently delete all the calendars you can access using Google Calendar.
     */
    public const HTTPS_WWW_GOOGLEAPIS_COM_AUTH_CALENDAR = 'https://www.googleapis.com/auth/calendar';

    private const _ALL_VALUES = [
        self::HTTPS_WWW_GOOGLEAPIS_COM_AUTH_CALENDAR_READONLY,
        self::HTTPS_WWW_GOOGLEAPIS_COM_AUTH_CALENDAR_EVENTS,
        self::HTTPS_WWW_GOOGLEAPIS_COM_AUTH_CALENDAR
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for OauthScope.");
    }
}
