<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models;

use CalendarApiLib\ApiHelper;
use stdClass;

/**
 * Office location details for a working location event.
 */
class OfficeLocation implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $buildingId;

    /**
     * @var string|null
     */
    private $floorId;

    /**
     * @var string|null
     */
    private $floorSectionId;

    /**
     * @var string|null
     */
    private $deskId;

    /**
     * @var string|null
     */
    private $label;

    /**
     * Returns Building Id.
     * Building identifier.
     */
    public function getBuildingId(): ?string
    {
        return $this->buildingId;
    }

    /**
     * Sets Building Id.
     * Building identifier.
     *
     * @maps buildingId
     */
    public function setBuildingId(?string $buildingId): void
    {
        $this->buildingId = $buildingId;
    }

    /**
     * Returns Floor Id.
     * Floor identifier.
     */
    public function getFloorId(): ?string
    {
        return $this->floorId;
    }

    /**
     * Sets Floor Id.
     * Floor identifier.
     *
     * @maps floorId
     */
    public function setFloorId(?string $floorId): void
    {
        $this->floorId = $floorId;
    }

    /**
     * Returns Floor Section Id.
     * Floor section identifier.
     */
    public function getFloorSectionId(): ?string
    {
        return $this->floorSectionId;
    }

    /**
     * Sets Floor Section Id.
     * Floor section identifier.
     *
     * @maps floorSectionId
     */
    public function setFloorSectionId(?string $floorSectionId): void
    {
        $this->floorSectionId = $floorSectionId;
    }

    /**
     * Returns Desk Id.
     * Desk identifier.
     */
    public function getDeskId(): ?string
    {
        return $this->deskId;
    }

    /**
     * Sets Desk Id.
     * Desk identifier.
     *
     * @maps deskId
     */
    public function setDeskId(?string $deskId): void
    {
        $this->deskId = $deskId;
    }

    /**
     * Returns Label.
     * Office name displayed in Calendar Web and Mobile clients.
     */
    public function getLabel(): ?string
    {
        return $this->label;
    }

    /**
     * Sets Label.
     * Office name displayed in Calendar Web and Mobile clients.
     *
     * @maps label
     */
    public function setLabel(?string $label): void
    {
        $this->label = $label;
    }

    /**
     * Converts the OfficeLocation object to a human-readable string representation.
     *
     * @return string The string representation of the OfficeLocation object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'OfficeLocation',
            [
                'buildingId' => $this->buildingId,
                'floorId' => $this->floorId,
                'floorSectionId' => $this->floorSectionId,
                'deskId' => $this->deskId,
                'label' => $this->label,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['buildingId', 'floorId', 'floorSectionId', 'deskId', 'label'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->buildingId)) {
            $json['buildingId']     = $this->buildingId;
        }
        if (isset($this->floorId)) {
            $json['floorId']        = $this->floorId;
        }
        if (isset($this->floorSectionId)) {
            $json['floorSectionId'] = $this->floorSectionId;
        }
        if (isset($this->deskId)) {
            $json['deskId']         = $this->deskId;
        }
        if (isset($this->label)) {
            $json['label']          = $this->label;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
