<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models;

use CalendarApiLib\ApiHelper;
use stdClass;

/**
 * A reminder for an event.
 */
class Reminder implements \JsonSerializable
{
    /**
     * @var string
     */
    private $method;

    /**
     * @var int
     */
    private $minutes;

    /**
     * @param string $method
     * @param int $minutes
     */
    public function __construct(string $method, int $minutes)
    {
        $this->method = $method;
        $this->minutes = $minutes;
    }

    /**
     * Returns Method.
     * The method used by a reminder.
     */
    public function getMethod(): string
    {
        return $this->method;
    }

    /**
     * Sets Method.
     * The method used by a reminder.
     *
     * @required
     * @maps method
     * @factory \CalendarApiLib\Models\ReminderMethod::checkValue
     */
    public function setMethod(string $method): void
    {
        $this->method = $method;
    }

    /**
     * Returns Minutes.
     * Number of minutes before the start of the event when the reminder should trigger. Valid values are
     * between 0 and 40320 (4 weeks).
     */
    public function getMinutes(): int
    {
        return $this->minutes;
    }

    /**
     * Sets Minutes.
     * Number of minutes before the start of the event when the reminder should trigger. Valid values are
     * between 0 and 40320 (4 weeks).
     *
     * @required
     * @maps minutes
     */
    public function setMinutes(int $minutes): void
    {
        $this->minutes = $minutes;
    }

    /**
     * Converts the Reminder object to a human-readable string representation.
     *
     * @return string The string representation of the Reminder object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Reminder',
            [
                'method' => $this->method,
                'minutes' => $this->minutes,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['method', 'minutes'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['method']  = ReminderMethod::checkValue($this->method);
        $json['minutes'] = $this->minutes;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
