<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models;

use CalendarApiLib\ApiHelper;
use stdClass;

/**
 * Request body to stop a push notification channel. Requires the channel ID and resourceId returned
 * from a previous watchEvents call.
 */
class StopChannelRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $id;

    /**
     * @var string
     */
    private $resourceId;

    /**
     * @param string $id
     * @param string $resourceId
     */
    public function __construct(string $id, string $resourceId)
    {
        $this->id = $id;
        $this->resourceId = $resourceId;
    }

    /**
     * Returns Id.
     * The UUID or unique string that identifies the channel, as provided when the channel was created.
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * The UUID or unique string that identifies the channel, as provided when the channel was created.
     *
     * @required
     * @maps id
     */
    public function setId(string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Resource Id.
     * An opaque ID that identifies the resource being watched on this channel. Returned in the watchEvents
     * response.
     */
    public function getResourceId(): string
    {
        return $this->resourceId;
    }

    /**
     * Sets Resource Id.
     * An opaque ID that identifies the resource being watched on this channel. Returned in the watchEvents
     * response.
     *
     * @required
     * @maps resourceId
     */
    public function setResourceId(string $resourceId): void
    {
        $this->resourceId = $resourceId;
    }

    /**
     * Converts the StopChannelRequest object to a human-readable string representation.
     *
     * @return string The string representation of the StopChannelRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'StopChannelRequest',
            [
                'id' => $this->id,
                'resourceId' => $this->resourceId,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['id', 'resourceId'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['id']         = $this->id;
        $json['resourceId'] = $this->resourceId;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
