<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models;

use CalendarApiLib\ApiHelper;
use CalendarApiLib\Utils\DateTimeHelper;
use stdClass;

/**
 * A time range representing a busy period.
 */
class TimePeriod implements \JsonSerializable
{
    /**
     * @var \DateTime|null
     */
    private $start;

    /**
     * @var \DateTime|null
     */
    private $end;

    /**
     * Returns Start.
     * The start of the busy time period (inclusive).
     */
    public function getStart(): ?\DateTime
    {
        return $this->start;
    }

    /**
     * Sets Start.
     * The start of the busy time period (inclusive).
     *
     * @maps start
     * @factory \CalendarApiLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setStart(?\DateTime $start): void
    {
        $this->start = $start;
    }

    /**
     * Returns End.
     * The end of the busy time period (exclusive).
     */
    public function getEnd(): ?\DateTime
    {
        return $this->end;
    }

    /**
     * Sets End.
     * The end of the busy time period (exclusive).
     *
     * @maps end
     * @factory \CalendarApiLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setEnd(?\DateTime $end): void
    {
        $this->end = $end;
    }

    /**
     * Converts the TimePeriod object to a human-readable string representation.
     *
     * @return string The string representation of the TimePeriod object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'TimePeriod',
            ['start' => $this->start, 'end' => $this->end, 'additionalProperties' => $this->additionalProperties]
        );
    }

    protected $propertyNames = ['start', 'end'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->start)) {
            $json['start'] = DateTimeHelper::toRfc3339DateTime($this->start);
        }
        if (isset($this->end)) {
            $json['end']   = DateTimeHelper::toRfc3339DateTime($this->end);
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
