<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models;

use CalendarApiLib\ApiHelper;
use stdClass;

/**
 * Request body to set up a push notification channel.
 */
class WatchRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $id;

    /**
     * @var string|null
     */
    private $token;

    /**
     * @var string
     */
    private $type;

    /**
     * @var string
     */
    private $address;

    /**
     * @var ChannelParams|null
     */
    private $params;

    /**
     * @param string $id
     * @param string $type
     * @param string $address
     */
    public function __construct(string $id, string $type, string $address)
    {
        $this->id = $id;
        $this->type = $type;
        $this->address = $address;
    }

    /**
     * Returns Id.
     * A UUID or similar unique string that identifies this channel.
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * A UUID or similar unique string that identifies this channel.
     *
     * @required
     * @maps id
     */
    public function setId(string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Token.
     * An arbitrary string delivered to the target address with each notification. Optional.
     */
    public function getToken(): ?string
    {
        return $this->token;
    }

    /**
     * Sets Token.
     * An arbitrary string delivered to the target address with each notification. Optional.
     *
     * @maps token
     */
    public function setToken(?string $token): void
    {
        $this->token = $token;
    }

    /**
     * Returns Type.
     * The type of delivery mechanism used for the notification channel.
     */
    public function getType(): string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * The type of delivery mechanism used for the notification channel.
     *
     * @required
     * @maps type
     * @factory \CalendarApiLib\Models\ChannelType::checkValue
     */
    public function setType(string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns Address.
     * The address where notifications are delivered for this channel. Must be HTTPS.
     */
    public function getAddress(): string
    {
        return $this->address;
    }

    /**
     * Sets Address.
     * The address where notifications are delivered for this channel. Must be HTTPS.
     *
     * @required
     * @maps address
     */
    public function setAddress(string $address): void
    {
        $this->address = $address;
    }

    /**
     * Returns Params.
     * Additional parameters controlling delivery channel behavior.
     */
    public function getParams(): ?ChannelParams
    {
        return $this->params;
    }

    /**
     * Sets Params.
     * Additional parameters controlling delivery channel behavior.
     *
     * @maps params
     */
    public function setParams(?ChannelParams $params): void
    {
        $this->params = $params;
    }

    /**
     * Converts the WatchRequest object to a human-readable string representation.
     *
     * @return string The string representation of the WatchRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'WatchRequest',
            [
                'id' => $this->id,
                'token' => $this->token,
                'type' => $this->type,
                'address' => $this->address,
                'params' => $this->params,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['id', 'token', 'type', 'address', 'params'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['id']         = $this->id;
        if (isset($this->token)) {
            $json['token']  = $this->token;
        }
        $json['type']       = ChannelType::checkValue($this->type);
        $json['address']    = $this->address;
        if (isset($this->params)) {
            $json['params'] = $this->params;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
