<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib\Models;

use CalendarApiLib\ApiHelper;
use stdClass;

/**
 * Working location event data. Used if eventType is workingLocation.
 */
class WorkingLocationProperties implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $type;

    /**
     * @var array|null
     */
    private $homeOffice;

    /**
     * @var OfficeLocation|null
     */
    private $officeLocation;

    /**
     * @var CustomLocation|null
     */
    private $customLocation;

    /**
     * Returns Type.
     * Type of working location.
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * Type of working location.
     *
     * @maps type
     * @factory \CalendarApiLib\Models\WorkingLocationType::checkValue
     */
    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns Home Office.
     * Indicates working from home. Present if type is homeOffice. Value is always an empty object.
     */
    public function getHomeOffice(): ?array
    {
        return $this->homeOffice;
    }

    /**
     * Sets Home Office.
     * Indicates working from home. Present if type is homeOffice. Value is always an empty object.
     *
     * @maps homeOffice
     */
    public function setHomeOffice(?array $homeOffice): void
    {
        $this->homeOffice = $homeOffice;
    }

    /**
     * Returns Office Location.
     * Office location details for a working location event.
     */
    public function getOfficeLocation(): ?OfficeLocation
    {
        return $this->officeLocation;
    }

    /**
     * Sets Office Location.
     * Office location details for a working location event.
     *
     * @maps officeLocation
     */
    public function setOfficeLocation(?OfficeLocation $officeLocation): void
    {
        $this->officeLocation = $officeLocation;
    }

    /**
     * Returns Custom Location.
     * Custom location details for a working location event.
     */
    public function getCustomLocation(): ?CustomLocation
    {
        return $this->customLocation;
    }

    /**
     * Sets Custom Location.
     * Custom location details for a working location event.
     *
     * @maps customLocation
     */
    public function setCustomLocation(?CustomLocation $customLocation): void
    {
        $this->customLocation = $customLocation;
    }

    /**
     * Converts the WorkingLocationProperties object to a human-readable string representation.
     *
     * @return string The string representation of the WorkingLocationProperties object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'WorkingLocationProperties',
            [
                'type' => $this->type,
                'homeOffice' => $this->homeOffice,
                'officeLocation' => $this->officeLocation,
                'customLocation' => $this->customLocation,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['type', 'homeOffice', 'officeLocation', 'customLocation'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->type)) {
            $json['type']           = WorkingLocationType::checkValue($this->type);
        }
        if (isset($this->homeOffice)) {
            $json['homeOffice']     = $this->homeOffice;
        }
        if (isset($this->officeLocation)) {
            $json['officeLocation'] = $this->officeLocation;
        }
        if (isset($this->customLocation)) {
            $json['customLocation'] = $this->customLocation;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
