<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib;

use CalendarApiLib\Apis\CalendarListApi;
use CalendarApiLib\Apis\ChannelsApi;
use CalendarApiLib\Apis\EventsApi;
use CalendarApiLib\Apis\FreeBusyApi;
use CalendarApiLib\Apis\OauthAuthorizationApi;
use CalendarApiLib\Authentication\AuthorizationCodeAuthCredentialsBuilder;
use CalendarApiLib\Authentication\AuthorizationCodeAuthManager;
use CalendarApiLib\Logging\LoggingConfigurationBuilder;
use CalendarApiLib\Logging\RequestLoggingConfigurationBuilder;
use CalendarApiLib\Logging\ResponseLoggingConfigurationBuilder;
use CalendarApiLib\Proxy\ProxyConfigurationBuilder;
use CalendarApiLib\Utils\CompatibilityConverter;
use Core\ClientBuilder;
use Core\Utils\CoreHelper;
use Unirest\Configuration;
use Unirest\HttpClient;

class CalendarApiClient implements ConfigurationInterface
{
    private $calendarList;

    private $events;

    private $freeBusy;

    private $channels;

    private $oauthAuthorization;

    private $authorizationCodeAuthManager;

    private $loggingConfigurationBuilder;

    private $proxyConfiguration;

    private $config;

    private $client;

    /**
     * @see CalendarApiClientBuilder::init()
     * @see CalendarApiClientBuilder::build()
     *
     * @param array $config
     */
    public function __construct(array $config = [])
    {
        $this->config = array_merge(ConfigurationDefaults::_ALL, CoreHelper::clone($config));
        $this->authorizationCodeAuthManager = new AuthorizationCodeAuthManager($this->config);
        $this->validateConfig();
        $loggingConfiguration = null;
        if ($this->config['loggingConfiguration'] instanceof LoggingConfigurationBuilder) {
            $this->loggingConfigurationBuilder = $this->config['loggingConfiguration'];
            $loggingConfiguration = $this->loggingConfigurationBuilder->build();
        }
        $this->proxyConfiguration = $this->config['proxyConfiguration'] ?? ConfigurationDefaults::PROXY_CONFIGURATION;
        $this->client = ClientBuilder::init(
            new HttpClient(Configuration::init($this)->proxyConfiguration($this->proxyConfiguration))
        )
            ->converter(new CompatibilityConverter())
            ->jsonHelper(ApiHelper::getJsonHelper())
            ->apiCallback($this->config['httpCallback'] ?? null)
            ->userAgent('PHP-SDK/1.0.2 (OS: {os-info}, Engine: {engine}/{engine-version})')
            ->serverUrls(self::ENVIRONMENT_MAP[$this->getEnvironment()], Server::DEFAULT_)
            ->authManagers(['oauth2' => $this->authorizationCodeAuthManager])
            ->loggingConfiguration($loggingConfiguration)
            ->build();
        $this->authorizationCodeAuthManager->setClient($this->client);
    }

    /**
     * Create a builder with the current client's configurations.
     *
     * @return CalendarApiClientBuilder CalendarApiClientBuilder instance
     */
    public function toBuilder(): CalendarApiClientBuilder
    {
        $builder = CalendarApiClientBuilder::init()
            ->timeout($this->getTimeout())
            ->enableRetries($this->shouldEnableRetries())
            ->numberOfRetries($this->getNumberOfRetries())
            ->retryInterval($this->getRetryInterval())
            ->backOffFactor($this->getBackOffFactor())
            ->maximumRetryWaitTime($this->getMaximumRetryWaitTime())
            ->retryOnTimeout($this->shouldRetryOnTimeout())
            ->httpStatusCodesToRetry($this->getHttpStatusCodesToRetry())
            ->httpMethodsToRetry($this->getHttpMethodsToRetry())
            ->environment($this->getEnvironment())
            ->httpCallback($this->config['httpCallback'] ?? null)
            ->proxyConfiguration($this->getProxyConfigurationBuilder());

        $authorizationCodeAuth = $this->getAuthorizationCodeAuthCredentialsBuilder();
        if ($authorizationCodeAuth != null) {
            $builder->authorizationCodeAuthCredentials($authorizationCodeAuth);
        }
        $loggingConfigurationBuilder = $this->getLoggingConfigurationBuilder();
        if ($loggingConfigurationBuilder != null) {
            $builder->loggingConfiguration($loggingConfigurationBuilder);
        }
        return $builder;
    }

    public function getTimeout(): int
    {
        return $this->config['timeout'] ?? ConfigurationDefaults::TIMEOUT;
    }

    public function shouldEnableRetries(): bool
    {
        return $this->config['enableRetries'] ?? ConfigurationDefaults::ENABLE_RETRIES;
    }

    public function getNumberOfRetries(): int
    {
        return $this->config['numberOfRetries'] ?? ConfigurationDefaults::NUMBER_OF_RETRIES;
    }

    public function getRetryInterval(): float
    {
        return $this->config['retryInterval'] ?? ConfigurationDefaults::RETRY_INTERVAL;
    }

    public function getBackOffFactor(): float
    {
        return $this->config['backOffFactor'] ?? ConfigurationDefaults::BACK_OFF_FACTOR;
    }

    public function getMaximumRetryWaitTime(): int
    {
        return $this->config['maximumRetryWaitTime'] ?? ConfigurationDefaults::MAXIMUM_RETRY_WAIT_TIME;
    }

    public function shouldRetryOnTimeout(): bool
    {
        return $this->config['retryOnTimeout'] ?? ConfigurationDefaults::RETRY_ON_TIMEOUT;
    }

    public function getHttpStatusCodesToRetry(): array
    {
        return $this->config['httpStatusCodesToRetry'] ?? ConfigurationDefaults::HTTP_STATUS_CODES_TO_RETRY;
    }

    public function getHttpMethodsToRetry(): array
    {
        return $this->config['httpMethodsToRetry'] ?? ConfigurationDefaults::HTTP_METHODS_TO_RETRY;
    }

    public function getEnvironment(): string
    {
        return $this->config['environment'] ?? ConfigurationDefaults::ENVIRONMENT;
    }

    public function getAuthorizationCodeAuth(): AuthorizationCodeAuth
    {
        return $this->authorizationCodeAuthManager;
    }

    public function getAuthorizationCodeAuthCredentialsBuilder(): ?AuthorizationCodeAuthCredentialsBuilder
    {
        if (
            empty($this->authorizationCodeAuthManager->getOauthClientId()) &&
            empty($this->authorizationCodeAuthManager->getOauthClientSecret()) &&
            empty($this->authorizationCodeAuthManager->getOauthRedirectUri())
        ) {
            return null;
        }
        return AuthorizationCodeAuthCredentialsBuilder::init(
            $this->authorizationCodeAuthManager->getOauthClientId(),
            $this->authorizationCodeAuthManager->getOauthClientSecret(),
            $this->authorizationCodeAuthManager->getOauthRedirectUri()
        )
            ->oauthToken($this->authorizationCodeAuthManager->getOauthToken())
            ->oauthScopes($this->authorizationCodeAuthManager->getOauthScopes());
    }

    public function getLoggingConfigurationBuilder(): ?LoggingConfigurationBuilder
    {
        if (is_null($this->loggingConfigurationBuilder)) {
            return null;
        }
        $config = $this->loggingConfigurationBuilder->getConfiguration();
        return LoggingConfigurationBuilder::init()
            ->level($config['level'])
            ->logger($config['logger'])
            ->maskSensitiveHeaders($config['maskSensitiveHeaders'])
            ->requestConfiguration(RequestLoggingConfigurationBuilder::init()
                ->includeQueryInPath($config['requestConfiguration']['includeQueryInPath'])
                ->body($config['requestConfiguration']['body'])
                ->headers($config['requestConfiguration']['headers'])
                ->includeHeaders(...$config['requestConfiguration']['includeHeaders'])
                ->excludeHeaders(...$config['requestConfiguration']['excludeHeaders'])
                ->unmaskHeaders(...$config['requestConfiguration']['unmaskHeaders']))
            ->responseConfiguration(ResponseLoggingConfigurationBuilder::init()
                ->body($config['responseConfiguration']['body'])
                ->headers($config['responseConfiguration']['headers'])
                ->includeHeaders(...$config['responseConfiguration']['includeHeaders'])
                ->excludeHeaders(...$config['responseConfiguration']['excludeHeaders'])
                ->unmaskHeaders(...$config['responseConfiguration']['unmaskHeaders']));
    }

    /**
     * Get the proxy configuration builder
     */
    public function getProxyConfigurationBuilder(): ProxyConfigurationBuilder
    {
        return ProxyConfigurationBuilder::init($this->proxyConfiguration['address'])
            ->port($this->proxyConfiguration['port'])
            ->tunnel($this->proxyConfiguration['tunnel'])
            ->auth($this->proxyConfiguration['auth']['user'], $this->proxyConfiguration['auth']['pass'])
            ->authMethod($this->proxyConfiguration['auth']['method']);
    }

    /**
     * Get the client configuration as an associative array
     *
     * @see CalendarApiClientBuilder::getConfiguration()
     */
    public function getConfiguration(): array
    {
        return $this->toBuilder()->getConfiguration();
    }

    /**
     * Clone this client and override given configuration options
     *
     * @see CalendarApiClientBuilder::build()
     */
    public function withConfiguration(array $config): self
    {
        return new self(array_merge($this->config, $config));
    }

    /**
     * Validate required configuration variables
     */
    private function validateConfig(): void
    {
        $builder = CalendarApiClientBuilder::init();

        $authorizationCodeAuth = $this->getAuthorizationCodeAuthCredentialsBuilder();
        if ($authorizationCodeAuth != null) {
            $builder->authorizationCodeAuthCredentials($authorizationCodeAuth);
        }
    }

    /**
     * Get the base uri for a given server in the current environment.
     *
     * @param string $server Server name
     *
     * @return string Base URI
     */
    public function getBaseUri(string $server = Server::DEFAULT_): string
    {
        return $this->client->getGlobalRequest($server)->getQueryUrl();
    }

    /**
     * Returns Calendar List Api
     */
    public function getCalendarListApi(): CalendarListApi
    {
        if ($this->calendarList == null) {
            $this->calendarList = new CalendarListApi($this->client);
        }
        return $this->calendarList;
    }

    /**
     * Returns Events Api
     */
    public function getEventsApi(): EventsApi
    {
        if ($this->events == null) {
            $this->events = new EventsApi($this->client);
        }
        return $this->events;
    }

    /**
     * Returns Free Busy Api
     */
    public function getFreeBusyApi(): FreeBusyApi
    {
        if ($this->freeBusy == null) {
            $this->freeBusy = new FreeBusyApi($this->client);
        }
        return $this->freeBusy;
    }

    /**
     * Returns Channels Api
     */
    public function getChannelsApi(): ChannelsApi
    {
        if ($this->channels == null) {
            $this->channels = new ChannelsApi($this->client);
        }
        return $this->channels;
    }

    /**
     * Returns Oauth Authorization Api
     */
    public function getOauthAuthorizationApi(): OauthAuthorizationApi
    {
        if ($this->oauthAuthorization == null) {
            $this->oauthAuthorization = new OauthAuthorizationApi($this->client);
        }
        return $this->oauthAuthorization;
    }

    /**
     * A map of all base urls used in different environments and servers
     *
     * @var array
     */
    private const ENVIRONMENT_MAP = [
        Environment::PRODUCTION => [
            Server::DEFAULT_ => 'https://www.googleapis.com/calendar/v3',
            Server::AUTH_SERVER => 'https://accounts.google.com/o/oauth2/v2',
            Server::ACCESS_TOKEN_SERVER => 'https://oauth2.googleapis.com'
        ]
    ];
}
