<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib;

use CalendarApiLib\Authentication\AuthorizationCodeAuthCredentialsBuilder;
use CalendarApiLib\Logging\LoggingConfigurationBuilder;
use CalendarApiLib\Proxy\ProxyConfigurationBuilder;
use CoreInterfaces\Http\HttpConfigurations;

/**
 * An interface for all configuration parameters required by the SDK.
 */
interface ConfigurationInterface extends HttpConfigurations
{
    /**
     * Get current API environment
     */
    public function getEnvironment(): string;

    /**
     * Get the credentials to use with AuthorizationCodeAuth
     */
    public function getAuthorizationCodeAuth(): AuthorizationCodeAuth;

    /**
     * Get the credentials builder instance to update credentials for AuthorizationCodeAuth
     */
    public function getAuthorizationCodeAuthCredentialsBuilder(): ?AuthorizationCodeAuthCredentialsBuilder;

    /**
     * Represents the logging configurations for API calls.
     */
    public function getLoggingConfigurationBuilder(): ?LoggingConfigurationBuilder;

    /**
     * Represents the proxy configurations for API calls.
     */
    public function getProxyConfigurationBuilder(): ProxyConfigurationBuilder;

    /**
     * Get the base uri for a given server in the current environment.
     *
     * @param string $server Server name
     *
     * @return string Base URI
     */
    public function getBaseUri(string $server = Server::DEFAULT_): string;
}
