<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib;

/**
 * Environments available for API
 */
class Environment
{
    /**
     * Google Calendar API v3
     */
    public const PRODUCTION = 'production';
}
