<?php

declare(strict_types=1);

/*
 * CalendarApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CalendarApiLib;

/**
 * Baseurl aliases
 */
class Server
{
    public const DEFAULT_ = 'default';

    public const AUTH_SERVER = 'auth server';

    public const ACCESS_TOKEN_SERVER = 'access token server';
}
